package com.hy.demo.mybatis.entity;

import java.util.Date;

public class CscLine extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.line_id
     *
     * @mbggenerated
     */
    private Long lineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.line_code
     *
     * @mbggenerated
     */
    private String lineCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.line_name
     *
     * @mbggenerated
     */
    private String lineName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.line_post
     *
     * @mbggenerated
     */
    private String linePost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.set_time
     *
     * @mbggenerated
     */
    private Integer setTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.station_count
     *
     * @mbggenerated
     */
    private Integer stationCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.equt_count
     *
     * @mbggenerated
     */
    private Integer equtCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.check_itme_count
     *
     * @mbggenerated
     */
    private Integer checkItmeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.cb_itme_count
     *
     * @mbggenerated
     */
    private Integer cbItmeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.charge_personid
     *
     * @mbggenerated
     */
    private String chargePersonid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.charge_person_name
     *
     * @mbggenerated
     */
    private String chargePersonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.isplan
     *
     * @mbggenerated
     */
    private Boolean isplan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.isenable
     *
     * @mbggenerated
     */
    private Boolean isenable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.org_id
     *
     * @mbggenerated
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.org_name
     *
     * @mbggenerated
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.created_dt
     *
     * @mbggenerated
     */
    private Date createdDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.created_by
     *
     * @mbggenerated
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.updated_by
     *
     * @mbggenerated
     */
    private Long updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.updated_dt
     *
     * @mbggenerated
     */
    private Date updatedDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.created_by_name
     *
     * @mbggenerated
     */
    private String createdByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.updated_by_name
     *
     * @mbggenerated
     */
    private String updatedByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.tenantid
     *
     * @mbggenerated
     */
    private Long tenantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.ver
     *
     * @mbggenerated
     */
    private Integer ver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.is_bluetooth_collect
     *
     * @mbggenerated
     */
    private Boolean isBluetoothCollect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.post_id
     *
     * @mbggenerated
     */
    private Long postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.post_name
     *
     * @mbggenerated
     */
    private String postName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.sign_method
     *
     * @mbggenerated
     */
    private String signMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.stopcheck_state
     *
     * @mbggenerated
     */
    private String stopcheckState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.frequency
     *
     * @mbggenerated
     */
    private String frequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.stopcause
     *
     * @mbggenerated
     */
    private String stopcause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.istj
     *
     * @mbggenerated
     */
    private Boolean istj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.force_photo
     *
     * @mbggenerated
     */
    private Boolean forcePhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.time_strategy_name
     *
     * @mbggenerated
     */
    private String timeStrategyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.time_strategy_id
     *
     * @mbggenerated
     */
    private Long timeStrategyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.longest_time
     *
     * @mbggenerated
     */
    private Integer longestTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.strategy_expression
     *
     * @mbggenerated
     */
    private String strategyExpression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.duration_control
     *
     * @mbggenerated
     */
    private Boolean durationControl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.time_range
     *
     * @mbggenerated
     */
    private String timeRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.is_auto_arrive
     *
     * @mbggenerated
     */
    private Boolean isAutoArrive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.is_jump_station
     *
     * @mbggenerated
     */
    private Boolean isJumpStation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.is_controltime
     *
     * @mbggenerated
     */
    private Integer isControltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.is_many_per
     *
     * @mbggenerated
     */
    private Integer isManyPer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.df
     *
     * @mbggenerated
     */
    private Boolean df;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line.attaches
     *
     * @mbggenerated
     */
    private String attaches;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.line_id
     *
     * @return the value of csc_line.line_id
     *
     * @mbggenerated
     */
    public Long getLineId() {
        return lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.line_id
     *
     * @param lineId the value for csc_line.line_id
     *
     * @mbggenerated
     */
    public void setLineId(Long lineId) {
        this.lineId = lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.line_code
     *
     * @return the value of csc_line.line_code
     *
     * @mbggenerated
     */
    public String getLineCode() {
        return lineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.line_code
     *
     * @param lineCode the value for csc_line.line_code
     *
     * @mbggenerated
     */
    public void setLineCode(String lineCode) {
        this.lineCode = lineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.line_name
     *
     * @return the value of csc_line.line_name
     *
     * @mbggenerated
     */
    public String getLineName() {
        return lineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.line_name
     *
     * @param lineName the value for csc_line.line_name
     *
     * @mbggenerated
     */
    public void setLineName(String lineName) {
        this.lineName = lineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.line_post
     *
     * @return the value of csc_line.line_post
     *
     * @mbggenerated
     */
    public String getLinePost() {
        return linePost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.line_post
     *
     * @param linePost the value for csc_line.line_post
     *
     * @mbggenerated
     */
    public void setLinePost(String linePost) {
        this.linePost = linePost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.set_time
     *
     * @return the value of csc_line.set_time
     *
     * @mbggenerated
     */
    public Integer getSetTime() {
        return setTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.set_time
     *
     * @param setTime the value for csc_line.set_time
     *
     * @mbggenerated
     */
    public void setSetTime(Integer setTime) {
        this.setTime = setTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.station_count
     *
     * @return the value of csc_line.station_count
     *
     * @mbggenerated
     */
    public Integer getStationCount() {
        return stationCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.station_count
     *
     * @param stationCount the value for csc_line.station_count
     *
     * @mbggenerated
     */
    public void setStationCount(Integer stationCount) {
        this.stationCount = stationCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.equt_count
     *
     * @return the value of csc_line.equt_count
     *
     * @mbggenerated
     */
    public Integer getEqutCount() {
        return equtCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.equt_count
     *
     * @param equtCount the value for csc_line.equt_count
     *
     * @mbggenerated
     */
    public void setEqutCount(Integer equtCount) {
        this.equtCount = equtCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.check_itme_count
     *
     * @return the value of csc_line.check_itme_count
     *
     * @mbggenerated
     */
    public Integer getCheckItmeCount() {
        return checkItmeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.check_itme_count
     *
     * @param checkItmeCount the value for csc_line.check_itme_count
     *
     * @mbggenerated
     */
    public void setCheckItmeCount(Integer checkItmeCount) {
        this.checkItmeCount = checkItmeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.cb_itme_count
     *
     * @return the value of csc_line.cb_itme_count
     *
     * @mbggenerated
     */
    public Integer getCbItmeCount() {
        return cbItmeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.cb_itme_count
     *
     * @param cbItmeCount the value for csc_line.cb_itme_count
     *
     * @mbggenerated
     */
    public void setCbItmeCount(Integer cbItmeCount) {
        this.cbItmeCount = cbItmeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.charge_personid
     *
     * @return the value of csc_line.charge_personid
     *
     * @mbggenerated
     */
    public String getChargePersonid() {
        return chargePersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.charge_personid
     *
     * @param chargePersonid the value for csc_line.charge_personid
     *
     * @mbggenerated
     */
    public void setChargePersonid(String chargePersonid) {
        this.chargePersonid = chargePersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.charge_person_name
     *
     * @return the value of csc_line.charge_person_name
     *
     * @mbggenerated
     */
    public String getChargePersonName() {
        return chargePersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.charge_person_name
     *
     * @param chargePersonName the value for csc_line.charge_person_name
     *
     * @mbggenerated
     */
    public void setChargePersonName(String chargePersonName) {
        this.chargePersonName = chargePersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.isplan
     *
     * @return the value of csc_line.isplan
     *
     * @mbggenerated
     */
    public Boolean getIsplan() {
        return isplan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.isplan
     *
     * @param isplan the value for csc_line.isplan
     *
     * @mbggenerated
     */
    public void setIsplan(Boolean isplan) {
        this.isplan = isplan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.isenable
     *
     * @return the value of csc_line.isenable
     *
     * @mbggenerated
     */
    public Boolean getIsenable() {
        return isenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.isenable
     *
     * @param isenable the value for csc_line.isenable
     *
     * @mbggenerated
     */
    public void setIsenable(Boolean isenable) {
        this.isenable = isenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.remark
     *
     * @return the value of csc_line.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.remark
     *
     * @param remark the value for csc_line.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.org_id
     *
     * @return the value of csc_line.org_id
     *
     * @mbggenerated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.org_id
     *
     * @param orgId the value for csc_line.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.org_name
     *
     * @return the value of csc_line.org_name
     *
     * @mbggenerated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.org_name
     *
     * @param orgName the value for csc_line.org_name
     *
     * @mbggenerated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.created_dt
     *
     * @return the value of csc_line.created_dt
     *
     * @mbggenerated
     */
    public Date getCreatedDt() {
        return createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.created_dt
     *
     * @param createdDt the value for csc_line.created_dt
     *
     * @mbggenerated
     */
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.created_by
     *
     * @return the value of csc_line.created_by
     *
     * @mbggenerated
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.created_by
     *
     * @param createdBy the value for csc_line.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.updated_by
     *
     * @return the value of csc_line.updated_by
     *
     * @mbggenerated
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.updated_by
     *
     * @param updatedBy the value for csc_line.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.updated_dt
     *
     * @return the value of csc_line.updated_dt
     *
     * @mbggenerated
     */
    public Date getUpdatedDt() {
        return updatedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.updated_dt
     *
     * @param updatedDt the value for csc_line.updated_dt
     *
     * @mbggenerated
     */
    public void setUpdatedDt(Date updatedDt) {
        this.updatedDt = updatedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.created_by_name
     *
     * @return the value of csc_line.created_by_name
     *
     * @mbggenerated
     */
    public String getCreatedByName() {
        return createdByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.created_by_name
     *
     * @param createdByName the value for csc_line.created_by_name
     *
     * @mbggenerated
     */
    public void setCreatedByName(String createdByName) {
        this.createdByName = createdByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.updated_by_name
     *
     * @return the value of csc_line.updated_by_name
     *
     * @mbggenerated
     */
    public String getUpdatedByName() {
        return updatedByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.updated_by_name
     *
     * @param updatedByName the value for csc_line.updated_by_name
     *
     * @mbggenerated
     */
    public void setUpdatedByName(String updatedByName) {
        this.updatedByName = updatedByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.tenantid
     *
     * @return the value of csc_line.tenantid
     *
     * @mbggenerated
     */
    public Long getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.tenantid
     *
     * @param tenantid the value for csc_line.tenantid
     *
     * @mbggenerated
     */
    public void setTenantid(Long tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.ver
     *
     * @return the value of csc_line.ver
     *
     * @mbggenerated
     */
    public Integer getVer() {
        return ver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.ver
     *
     * @param ver the value for csc_line.ver
     *
     * @mbggenerated
     */
    public void setVer(Integer ver) {
        this.ver = ver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.is_bluetooth_collect
     *
     * @return the value of csc_line.is_bluetooth_collect
     *
     * @mbggenerated
     */
    public Boolean getIsBluetoothCollect() {
        return isBluetoothCollect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.is_bluetooth_collect
     *
     * @param isBluetoothCollect the value for csc_line.is_bluetooth_collect
     *
     * @mbggenerated
     */
    public void setIsBluetoothCollect(Boolean isBluetoothCollect) {
        this.isBluetoothCollect = isBluetoothCollect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.post_id
     *
     * @return the value of csc_line.post_id
     *
     * @mbggenerated
     */
    public Long getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.post_id
     *
     * @param postId the value for csc_line.post_id
     *
     * @mbggenerated
     */
    public void setPostId(Long postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.post_name
     *
     * @return the value of csc_line.post_name
     *
     * @mbggenerated
     */
    public String getPostName() {
        return postName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.post_name
     *
     * @param postName the value for csc_line.post_name
     *
     * @mbggenerated
     */
    public void setPostName(String postName) {
        this.postName = postName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.sign_method
     *
     * @return the value of csc_line.sign_method
     *
     * @mbggenerated
     */
    public String getSignMethod() {
        return signMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.sign_method
     *
     * @param signMethod the value for csc_line.sign_method
     *
     * @mbggenerated
     */
    public void setSignMethod(String signMethod) {
        this.signMethod = signMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.stopcheck_state
     *
     * @return the value of csc_line.stopcheck_state
     *
     * @mbggenerated
     */
    public String getStopcheckState() {
        return stopcheckState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.stopcheck_state
     *
     * @param stopcheckState the value for csc_line.stopcheck_state
     *
     * @mbggenerated
     */
    public void setStopcheckState(String stopcheckState) {
        this.stopcheckState = stopcheckState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.frequency
     *
     * @return the value of csc_line.frequency
     *
     * @mbggenerated
     */
    public String getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.frequency
     *
     * @param frequency the value for csc_line.frequency
     *
     * @mbggenerated
     */
    public void setFrequency(String frequency) {
        this.frequency = frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.stopcause
     *
     * @return the value of csc_line.stopcause
     *
     * @mbggenerated
     */
    public String getStopcause() {
        return stopcause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.stopcause
     *
     * @param stopcause the value for csc_line.stopcause
     *
     * @mbggenerated
     */
    public void setStopcause(String stopcause) {
        this.stopcause = stopcause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.istj
     *
     * @return the value of csc_line.istj
     *
     * @mbggenerated
     */
    public Boolean getIstj() {
        return istj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.istj
     *
     * @param istj the value for csc_line.istj
     *
     * @mbggenerated
     */
    public void setIstj(Boolean istj) {
        this.istj = istj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.force_photo
     *
     * @return the value of csc_line.force_photo
     *
     * @mbggenerated
     */
    public Boolean getForcePhoto() {
        return forcePhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.force_photo
     *
     * @param forcePhoto the value for csc_line.force_photo
     *
     * @mbggenerated
     */
    public void setForcePhoto(Boolean forcePhoto) {
        this.forcePhoto = forcePhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.time_strategy_name
     *
     * @return the value of csc_line.time_strategy_name
     *
     * @mbggenerated
     */
    public String getTimeStrategyName() {
        return timeStrategyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.time_strategy_name
     *
     * @param timeStrategyName the value for csc_line.time_strategy_name
     *
     * @mbggenerated
     */
    public void setTimeStrategyName(String timeStrategyName) {
        this.timeStrategyName = timeStrategyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.time_strategy_id
     *
     * @return the value of csc_line.time_strategy_id
     *
     * @mbggenerated
     */
    public Long getTimeStrategyId() {
        return timeStrategyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.time_strategy_id
     *
     * @param timeStrategyId the value for csc_line.time_strategy_id
     *
     * @mbggenerated
     */
    public void setTimeStrategyId(Long timeStrategyId) {
        this.timeStrategyId = timeStrategyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.longest_time
     *
     * @return the value of csc_line.longest_time
     *
     * @mbggenerated
     */
    public Integer getLongestTime() {
        return longestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.longest_time
     *
     * @param longestTime the value for csc_line.longest_time
     *
     * @mbggenerated
     */
    public void setLongestTime(Integer longestTime) {
        this.longestTime = longestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.strategy_expression
     *
     * @return the value of csc_line.strategy_expression
     *
     * @mbggenerated
     */
    public String getStrategyExpression() {
        return strategyExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.strategy_expression
     *
     * @param strategyExpression the value for csc_line.strategy_expression
     *
     * @mbggenerated
     */
    public void setStrategyExpression(String strategyExpression) {
        this.strategyExpression = strategyExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.duration_control
     *
     * @return the value of csc_line.duration_control
     *
     * @mbggenerated
     */
    public Boolean getDurationControl() {
        return durationControl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.duration_control
     *
     * @param durationControl the value for csc_line.duration_control
     *
     * @mbggenerated
     */
    public void setDurationControl(Boolean durationControl) {
        this.durationControl = durationControl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.time_range
     *
     * @return the value of csc_line.time_range
     *
     * @mbggenerated
     */
    public String getTimeRange() {
        return timeRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.time_range
     *
     * @param timeRange the value for csc_line.time_range
     *
     * @mbggenerated
     */
    public void setTimeRange(String timeRange) {
        this.timeRange = timeRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.is_auto_arrive
     *
     * @return the value of csc_line.is_auto_arrive
     *
     * @mbggenerated
     */
    public Boolean getIsAutoArrive() {
        return isAutoArrive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.is_auto_arrive
     *
     * @param isAutoArrive the value for csc_line.is_auto_arrive
     *
     * @mbggenerated
     */
    public void setIsAutoArrive(Boolean isAutoArrive) {
        this.isAutoArrive = isAutoArrive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.is_jump_station
     *
     * @return the value of csc_line.is_jump_station
     *
     * @mbggenerated
     */
    public Boolean getIsJumpStation() {
        return isJumpStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.is_jump_station
     *
     * @param isJumpStation the value for csc_line.is_jump_station
     *
     * @mbggenerated
     */
    public void setIsJumpStation(Boolean isJumpStation) {
        this.isJumpStation = isJumpStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.is_controltime
     *
     * @return the value of csc_line.is_controltime
     *
     * @mbggenerated
     */
    public Integer getIsControltime() {
        return isControltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.is_controltime
     *
     * @param isControltime the value for csc_line.is_controltime
     *
     * @mbggenerated
     */
    public void setIsControltime(Integer isControltime) {
        this.isControltime = isControltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.is_many_per
     *
     * @return the value of csc_line.is_many_per
     *
     * @mbggenerated
     */
    public Integer getIsManyPer() {
        return isManyPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.is_many_per
     *
     * @param isManyPer the value for csc_line.is_many_per
     *
     * @mbggenerated
     */
    public void setIsManyPer(Integer isManyPer) {
        this.isManyPer = isManyPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.df
     *
     * @return the value of csc_line.df
     *
     * @mbggenerated
     */
    public Boolean getDf() {
        return df;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.df
     *
     * @param df the value for csc_line.df
     *
     * @mbggenerated
     */
    public void setDf(Boolean df) {
        this.df = df;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line.attaches
     *
     * @return the value of csc_line.attaches
     *
     * @mbggenerated
     */
    public String getAttaches() {
        return attaches;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line.attaches
     *
     * @param attaches the value for csc_line.attaches
     *
     * @mbggenerated
     */
    public void setAttaches(String attaches) {
        this.attaches = attaches;
    }

    @Override
    public String toString() {
        return "CscLine{" +
                "lineId=" + lineId +
                ", lineCode='" + lineCode + '\'' +
                ", lineName='" + lineName + '\'' +
                ", linePost='" + linePost + '\'' +
                ", setTime=" + setTime +
                ", stationCount=" + stationCount +
                ", equtCount=" + equtCount +
                ", checkItmeCount=" + checkItmeCount +
                ", cbItmeCount=" + cbItmeCount +
                ", chargePersonid='" + chargePersonid + '\'' +
                ", chargePersonName='" + chargePersonName + '\'' +
                ", isplan=" + isplan +
                ", isenable=" + isenable +
                ", remark='" + remark + '\'' +
                ", orgId=" + orgId +
                ", orgName='" + orgName + '\'' +
                ", createdDt=" + createdDt +
                ", createdBy=" + createdBy +
                ", updatedBy=" + updatedBy +
                ", updatedDt=" + updatedDt +
                ", createdByName='" + createdByName + '\'' +
                ", updatedByName='" + updatedByName + '\'' +
                ", tenantid=" + tenantid +
                ", ver=" + ver +
                ", isBluetoothCollect=" + isBluetoothCollect +
                ", postId=" + postId +
                ", postName='" + postName + '\'' +
                ", signMethod='" + signMethod + '\'' +
                ", stopcheckState='" + stopcheckState + '\'' +
                ", frequency='" + frequency + '\'' +
                ", stopcause='" + stopcause + '\'' +
                ", istj=" + istj +
                ", forcePhoto=" + forcePhoto +
                ", timeStrategyName='" + timeStrategyName + '\'' +
                ", timeStrategyId=" + timeStrategyId +
                ", longestTime=" + longestTime +
                ", strategyExpression='" + strategyExpression + '\'' +
                ", durationControl=" + durationControl +
                ", timeRange='" + timeRange + '\'' +
                ", isAutoArrive=" + isAutoArrive +
                ", isJumpStation=" + isJumpStation +
                ", isControltime=" + isControltime +
                ", isManyPer=" + isManyPer +
                ", df=" + df +
                ", attaches='" + attaches + '\'' +
                '}';
    }
}