package com.hy.demo.mybatis.entity;

import java.math.BigDecimal;
import java.util.Date;

public class CscLineStation extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.line_station_id
     *
     * @mbggenerated
     */
    private Long lineStationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.station_id
     *
     * @mbggenerated
     */
    private Long stationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.station_name
     *
     * @mbggenerated
     */
    private String stationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.station_code
     *
     * @mbggenerated
     */
    private String stationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.line_id
     *
     * @mbggenerated
     */
    private Long lineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.line_name
     *
     * @mbggenerated
     */
    private String lineName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.isenable
     *
     * @mbggenerated
     */
    private Boolean isenable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.seq
     *
     * @mbggenerated
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.card_no
     *
     * @mbggenerated
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.gps_x
     *
     * @mbggenerated
     */
    private BigDecimal gpsX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.gps_y
     *
     * @mbggenerated
     */
    private BigDecimal gpsY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.radius
     *
     * @mbggenerated
     */
    private Integer radius;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.org_id
     *
     * @mbggenerated
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.org_name
     *
     * @mbggenerated
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.created_dt
     *
     * @mbggenerated
     */
    private Date createdDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.created_by
     *
     * @mbggenerated
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.updated_by
     *
     * @mbggenerated
     */
    private Long updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.updated_dt
     *
     * @mbggenerated
     */
    private Date updatedDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.created_by_name
     *
     * @mbggenerated
     */
    private String createdByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.updated_by_name
     *
     * @mbggenerated
     */
    private String updatedByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.tenantid
     *
     * @mbggenerated
     */
    private Long tenantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.ver
     *
     * @mbggenerated
     */
    private Integer ver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.blue_name
     *
     * @mbggenerated
     */
    private String blueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.blue_mac
     *
     * @mbggenerated
     */
    private String blueMac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.stopcheck_state
     *
     * @mbggenerated
     */
    private String stopcheckState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.strategy_name
     *
     * @mbggenerated
     */
    private String strategyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.stopcause
     *
     * @mbggenerated
     */
    private String stopcause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.strategy_expression
     *
     * @mbggenerated
     */
    private String strategyExpression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.belongsequ
     *
     * @mbggenerated
     */
    private String belongsequ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.station_time
     *
     * @mbggenerated
     */
    private Integer stationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.time_strategy_id
     *
     * @mbggenerated
     */
    private Long timeStrategyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.sign_method
     *
     * @mbggenerated
     */
    private String signMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.is_all_normal
     *
     * @mbggenerated
     */
    private Boolean isAllNormal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.df
     *
     * @mbggenerated
     */
    private Boolean df;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_line_station.attaches
     *
     * @mbggenerated
     */
    private String attaches;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.line_station_id
     *
     * @return the value of csc_line_station.line_station_id
     *
     * @mbggenerated
     */
    public Long getLineStationId() {
        return lineStationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.line_station_id
     *
     * @param lineStationId the value for csc_line_station.line_station_id
     *
     * @mbggenerated
     */
    public void setLineStationId(Long lineStationId) {
        this.lineStationId = lineStationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.station_id
     *
     * @return the value of csc_line_station.station_id
     *
     * @mbggenerated
     */
    public Long getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.station_id
     *
     * @param stationId the value for csc_line_station.station_id
     *
     * @mbggenerated
     */
    public void setStationId(Long stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.station_name
     *
     * @return the value of csc_line_station.station_name
     *
     * @mbggenerated
     */
    public String getStationName() {
        return stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.station_name
     *
     * @param stationName the value for csc_line_station.station_name
     *
     * @mbggenerated
     */
    public void setStationName(String stationName) {
        this.stationName = stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.station_code
     *
     * @return the value of csc_line_station.station_code
     *
     * @mbggenerated
     */
    public String getStationCode() {
        return stationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.station_code
     *
     * @param stationCode the value for csc_line_station.station_code
     *
     * @mbggenerated
     */
    public void setStationCode(String stationCode) {
        this.stationCode = stationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.line_id
     *
     * @return the value of csc_line_station.line_id
     *
     * @mbggenerated
     */
    public Long getLineId() {
        return lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.line_id
     *
     * @param lineId the value for csc_line_station.line_id
     *
     * @mbggenerated
     */
    public void setLineId(Long lineId) {
        this.lineId = lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.line_name
     *
     * @return the value of csc_line_station.line_name
     *
     * @mbggenerated
     */
    public String getLineName() {
        return lineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.line_name
     *
     * @param lineName the value for csc_line_station.line_name
     *
     * @mbggenerated
     */
    public void setLineName(String lineName) {
        this.lineName = lineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.isenable
     *
     * @return the value of csc_line_station.isenable
     *
     * @mbggenerated
     */
    public Boolean getIsenable() {
        return isenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.isenable
     *
     * @param isenable the value for csc_line_station.isenable
     *
     * @mbggenerated
     */
    public void setIsenable(Boolean isenable) {
        this.isenable = isenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.seq
     *
     * @return the value of csc_line_station.seq
     *
     * @mbggenerated
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.seq
     *
     * @param seq the value for csc_line_station.seq
     *
     * @mbggenerated
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.card_no
     *
     * @return the value of csc_line_station.card_no
     *
     * @mbggenerated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.card_no
     *
     * @param cardNo the value for csc_line_station.card_no
     *
     * @mbggenerated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.gps_x
     *
     * @return the value of csc_line_station.gps_x
     *
     * @mbggenerated
     */
    public BigDecimal getGpsX() {
        return gpsX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.gps_x
     *
     * @param gpsX the value for csc_line_station.gps_x
     *
     * @mbggenerated
     */
    public void setGpsX(BigDecimal gpsX) {
        this.gpsX = gpsX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.gps_y
     *
     * @return the value of csc_line_station.gps_y
     *
     * @mbggenerated
     */
    public BigDecimal getGpsY() {
        return gpsY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.gps_y
     *
     * @param gpsY the value for csc_line_station.gps_y
     *
     * @mbggenerated
     */
    public void setGpsY(BigDecimal gpsY) {
        this.gpsY = gpsY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.radius
     *
     * @return the value of csc_line_station.radius
     *
     * @mbggenerated
     */
    public Integer getRadius() {
        return radius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.radius
     *
     * @param radius the value for csc_line_station.radius
     *
     * @mbggenerated
     */
    public void setRadius(Integer radius) {
        this.radius = radius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.remark
     *
     * @return the value of csc_line_station.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.remark
     *
     * @param remark the value for csc_line_station.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.org_id
     *
     * @return the value of csc_line_station.org_id
     *
     * @mbggenerated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.org_id
     *
     * @param orgId the value for csc_line_station.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.org_name
     *
     * @return the value of csc_line_station.org_name
     *
     * @mbggenerated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.org_name
     *
     * @param orgName the value for csc_line_station.org_name
     *
     * @mbggenerated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.created_dt
     *
     * @return the value of csc_line_station.created_dt
     *
     * @mbggenerated
     */
    public Date getCreatedDt() {
        return createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.created_dt
     *
     * @param createdDt the value for csc_line_station.created_dt
     *
     * @mbggenerated
     */
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.created_by
     *
     * @return the value of csc_line_station.created_by
     *
     * @mbggenerated
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.created_by
     *
     * @param createdBy the value for csc_line_station.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.updated_by
     *
     * @return the value of csc_line_station.updated_by
     *
     * @mbggenerated
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.updated_by
     *
     * @param updatedBy the value for csc_line_station.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.updated_dt
     *
     * @return the value of csc_line_station.updated_dt
     *
     * @mbggenerated
     */
    public Date getUpdatedDt() {
        return updatedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.updated_dt
     *
     * @param updatedDt the value for csc_line_station.updated_dt
     *
     * @mbggenerated
     */
    public void setUpdatedDt(Date updatedDt) {
        this.updatedDt = updatedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.created_by_name
     *
     * @return the value of csc_line_station.created_by_name
     *
     * @mbggenerated
     */
    public String getCreatedByName() {
        return createdByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.created_by_name
     *
     * @param createdByName the value for csc_line_station.created_by_name
     *
     * @mbggenerated
     */
    public void setCreatedByName(String createdByName) {
        this.createdByName = createdByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.updated_by_name
     *
     * @return the value of csc_line_station.updated_by_name
     *
     * @mbggenerated
     */
    public String getUpdatedByName() {
        return updatedByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.updated_by_name
     *
     * @param updatedByName the value for csc_line_station.updated_by_name
     *
     * @mbggenerated
     */
    public void setUpdatedByName(String updatedByName) {
        this.updatedByName = updatedByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.tenantid
     *
     * @return the value of csc_line_station.tenantid
     *
     * @mbggenerated
     */
    public Long getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.tenantid
     *
     * @param tenantid the value for csc_line_station.tenantid
     *
     * @mbggenerated
     */
    public void setTenantid(Long tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.ver
     *
     * @return the value of csc_line_station.ver
     *
     * @mbggenerated
     */
    public Integer getVer() {
        return ver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.ver
     *
     * @param ver the value for csc_line_station.ver
     *
     * @mbggenerated
     */
    public void setVer(Integer ver) {
        this.ver = ver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.blue_name
     *
     * @return the value of csc_line_station.blue_name
     *
     * @mbggenerated
     */
    public String getBlueName() {
        return blueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.blue_name
     *
     * @param blueName the value for csc_line_station.blue_name
     *
     * @mbggenerated
     */
    public void setBlueName(String blueName) {
        this.blueName = blueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.blue_mac
     *
     * @return the value of csc_line_station.blue_mac
     *
     * @mbggenerated
     */
    public String getBlueMac() {
        return blueMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.blue_mac
     *
     * @param blueMac the value for csc_line_station.blue_mac
     *
     * @mbggenerated
     */
    public void setBlueMac(String blueMac) {
        this.blueMac = blueMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.stopcheck_state
     *
     * @return the value of csc_line_station.stopcheck_state
     *
     * @mbggenerated
     */
    public String getStopcheckState() {
        return stopcheckState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.stopcheck_state
     *
     * @param stopcheckState the value for csc_line_station.stopcheck_state
     *
     * @mbggenerated
     */
    public void setStopcheckState(String stopcheckState) {
        this.stopcheckState = stopcheckState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.strategy_name
     *
     * @return the value of csc_line_station.strategy_name
     *
     * @mbggenerated
     */
    public String getStrategyName() {
        return strategyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.strategy_name
     *
     * @param strategyName the value for csc_line_station.strategy_name
     *
     * @mbggenerated
     */
    public void setStrategyName(String strategyName) {
        this.strategyName = strategyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.stopcause
     *
     * @return the value of csc_line_station.stopcause
     *
     * @mbggenerated
     */
    public String getStopcause() {
        return stopcause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.stopcause
     *
     * @param stopcause the value for csc_line_station.stopcause
     *
     * @mbggenerated
     */
    public void setStopcause(String stopcause) {
        this.stopcause = stopcause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.strategy_expression
     *
     * @return the value of csc_line_station.strategy_expression
     *
     * @mbggenerated
     */
    public String getStrategyExpression() {
        return strategyExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.strategy_expression
     *
     * @param strategyExpression the value for csc_line_station.strategy_expression
     *
     * @mbggenerated
     */
    public void setStrategyExpression(String strategyExpression) {
        this.strategyExpression = strategyExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.belongsequ
     *
     * @return the value of csc_line_station.belongsequ
     *
     * @mbggenerated
     */
    public String getBelongsequ() {
        return belongsequ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.belongsequ
     *
     * @param belongsequ the value for csc_line_station.belongsequ
     *
     * @mbggenerated
     */
    public void setBelongsequ(String belongsequ) {
        this.belongsequ = belongsequ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.station_time
     *
     * @return the value of csc_line_station.station_time
     *
     * @mbggenerated
     */
    public Integer getStationTime() {
        return stationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.station_time
     *
     * @param stationTime the value for csc_line_station.station_time
     *
     * @mbggenerated
     */
    public void setStationTime(Integer stationTime) {
        this.stationTime = stationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.time_strategy_id
     *
     * @return the value of csc_line_station.time_strategy_id
     *
     * @mbggenerated
     */
    public Long getTimeStrategyId() {
        return timeStrategyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.time_strategy_id
     *
     * @param timeStrategyId the value for csc_line_station.time_strategy_id
     *
     * @mbggenerated
     */
    public void setTimeStrategyId(Long timeStrategyId) {
        this.timeStrategyId = timeStrategyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.sign_method
     *
     * @return the value of csc_line_station.sign_method
     *
     * @mbggenerated
     */
    public String getSignMethod() {
        return signMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.sign_method
     *
     * @param signMethod the value for csc_line_station.sign_method
     *
     * @mbggenerated
     */
    public void setSignMethod(String signMethod) {
        this.signMethod = signMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.is_all_normal
     *
     * @return the value of csc_line_station.is_all_normal
     *
     * @mbggenerated
     */
    public Boolean getIsAllNormal() {
        return isAllNormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.is_all_normal
     *
     * @param isAllNormal the value for csc_line_station.is_all_normal
     *
     * @mbggenerated
     */
    public void setIsAllNormal(Boolean isAllNormal) {
        this.isAllNormal = isAllNormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.df
     *
     * @return the value of csc_line_station.df
     *
     * @mbggenerated
     */
    public Boolean getDf() {
        return df;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.df
     *
     * @param df the value for csc_line_station.df
     *
     * @mbggenerated
     */
    public void setDf(Boolean df) {
        this.df = df;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_line_station.attaches
     *
     * @return the value of csc_line_station.attaches
     *
     * @mbggenerated
     */
    public String getAttaches() {
        return attaches;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_line_station.attaches
     *
     * @param attaches the value for csc_line_station.attaches
     *
     * @mbggenerated
     */
    public void setAttaches(String attaches) {
        this.attaches = attaches;
    }

    @Override
    public String toString() {
        return "CscLineStation{" +
                "lineStationId=" + lineStationId +
                ", stationId=" + stationId +
                ", stationName='" + stationName + '\'' +
                ", stationCode='" + stationCode + '\'' +
                ", lineId=" + lineId +
                ", lineName='" + lineName + '\'' +
                ", isenable=" + isenable +
                ", seq=" + seq +
                ", cardNo='" + cardNo + '\'' +
                ", gpsX=" + gpsX +
                ", gpsY=" + gpsY +
                ", radius=" + radius +
                ", remark='" + remark + '\'' +
                ", orgId=" + orgId +
                ", orgName='" + orgName + '\'' +
                ", createdDt=" + createdDt +
                ", createdBy=" + createdBy +
                ", updatedBy=" + updatedBy +
                ", updatedDt=" + updatedDt +
                ", createdByName='" + createdByName + '\'' +
                ", updatedByName='" + updatedByName + '\'' +
                ", tenantid=" + tenantid +
                ", ver=" + ver +
                ", blueName='" + blueName + '\'' +
                ", blueMac='" + blueMac + '\'' +
                ", stopcheckState='" + stopcheckState + '\'' +
                ", strategyName='" + strategyName + '\'' +
                ", stopcause='" + stopcause + '\'' +
                ", strategyExpression='" + strategyExpression + '\'' +
                ", belongsequ='" + belongsequ + '\'' +
                ", stationTime=" + stationTime +
                ", timeStrategyId=" + timeStrategyId +
                ", signMethod='" + signMethod + '\'' +
                ", isAllNormal=" + isAllNormal +
                ", df=" + df +
                ", attaches='" + attaches + '\'' +
                '}';
    }
}