package com.hy.demo.mybatis.entity;

import java.util.Date;

public class CscTask extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.task_id
     *
     * @mbggenerated
     */
    private Long taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.task_code
     *
     * @mbggenerated
     */
    private String taskCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.task_name
     *
     * @mbggenerated
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.task_date
     *
     * @mbggenerated
     */
    private Date taskDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.plan_start_time
     *
     * @mbggenerated
     */
    private Date planStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.plan_end_time
     *
     * @mbggenerated
     */
    private Date planEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.task_start_time
     *
     * @mbggenerated
     */
    private Date taskStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.task_end_time
     *
     * @mbggenerated
     */
    private Date taskEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.is_plan
     *
     * @mbggenerated
     */
    private Boolean isPlan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.set_time
     *
     * @mbggenerated
     */
    private Integer setTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.real_time
     *
     * @mbggenerated
     */
    private Integer realTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.task_status
     *
     * @mbggenerated
     */
    private String taskStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.post
     *
     * @mbggenerated
     */
    private String post;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.person_id
     *
     * @mbggenerated
     */
    private String personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.person_name
     *
     * @mbggenerated
     */
    private String personName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.task_per_name
     *
     * @mbggenerated
     */
    private String taskPerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.upload_per_id
     *
     * @mbggenerated
     */
    private Long uploadPerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.upload_per_name
     *
     * @mbggenerated
     */
    private String uploadPerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.upload_time
     *
     * @mbggenerated
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.upload_phone
     *
     * @mbggenerated
     */
    private String uploadPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.line_id
     *
     * @mbggenerated
     */
    private Long lineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.line_name
     *
     * @mbggenerated
     */
    private String lineName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.class_id
     *
     * @mbggenerated
     */
    private Long classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.class_name
     *
     * @mbggenerated
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.round_id
     *
     * @mbggenerated
     */
    private Long roundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.round_name
     *
     * @mbggenerated
     */
    private String roundName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.last_task_id
     *
     * @mbggenerated
     */
    private Long lastTaskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.task_type
     *
     * @mbggenerated
     */
    private String taskType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.org_id
     *
     * @mbggenerated
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.org_name
     *
     * @mbggenerated
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.created_dt
     *
     * @mbggenerated
     */
    private Date createdDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.created_by
     *
     * @mbggenerated
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.updated_by
     *
     * @mbggenerated
     */
    private Long updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.updated_dt
     *
     * @mbggenerated
     */
    private Date updatedDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.created_by_name
     *
     * @mbggenerated
     */
    private String createdByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.updated_by_name
     *
     * @mbggenerated
     */
    private String updatedByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.tenantid
     *
     * @mbggenerated
     */
    private Long tenantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.ver
     *
     * @mbggenerated
     */
    private Integer ver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.is_bluetooth_collect
     *
     * @mbggenerated
     */
    private Boolean isBluetoothCollect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.post_id
     *
     * @mbggenerated
     */
    private Long postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.post_name
     *
     * @mbggenerated
     */
    private String postName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.sign_method
     *
     * @mbggenerated
     */
    private String signMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.person_nfccard
     *
     * @mbggenerated
     */
    private String personNfccard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.step_number
     *
     * @mbggenerated
     */
    private Integer stepNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.stopcheck_state
     *
     * @mbggenerated
     */
    private String stopcheckState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.org_code
     *
     * @mbggenerated
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.download_status
     *
     * @mbggenerated
     */
    private Byte downloadStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.duration_control
     *
     * @mbggenerated
     */
    private Boolean durationControl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.time_range
     *
     * @mbggenerated
     */
    private String timeRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.is_auto_arrive
     *
     * @mbggenerated
     */
    private Boolean isAutoArrive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.is_jump_station
     *
     * @mbggenerated
     */
    private Boolean isJumpStation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.force_photo
     *
     * @mbggenerated
     */
    private Boolean forcePhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.is_punctual
     *
     * @mbggenerated
     */
    private Boolean isPunctual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.charger_id
     *
     * @mbggenerated
     */
    private String chargerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.charger_name
     *
     * @mbggenerated
     */
    private String chargerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.is_controltime
     *
     * @mbggenerated
     */
    private Integer isControltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.is_many_per
     *
     * @mbggenerated
     */
    private Integer isManyPer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task.df
     *
     * @mbggenerated
     */
    private Boolean df;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.task_id
     *
     * @return the value of csc_task.task_id
     *
     * @mbggenerated
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.task_id
     *
     * @param taskId the value for csc_task.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.task_code
     *
     * @return the value of csc_task.task_code
     *
     * @mbggenerated
     */
    public String getTaskCode() {
        return taskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.task_code
     *
     * @param taskCode the value for csc_task.task_code
     *
     * @mbggenerated
     */
    public void setTaskCode(String taskCode) {
        this.taskCode = taskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.task_name
     *
     * @return the value of csc_task.task_name
     *
     * @mbggenerated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.task_name
     *
     * @param taskName the value for csc_task.task_name
     *
     * @mbggenerated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.task_date
     *
     * @return the value of csc_task.task_date
     *
     * @mbggenerated
     */
    public Date getTaskDate() {
        return taskDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.task_date
     *
     * @param taskDate the value for csc_task.task_date
     *
     * @mbggenerated
     */
    public void setTaskDate(Date taskDate) {
        this.taskDate = taskDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.plan_start_time
     *
     * @return the value of csc_task.plan_start_time
     *
     * @mbggenerated
     */
    public Date getPlanStartTime() {
        return planStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.plan_start_time
     *
     * @param planStartTime the value for csc_task.plan_start_time
     *
     * @mbggenerated
     */
    public void setPlanStartTime(Date planStartTime) {
        this.planStartTime = planStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.plan_end_time
     *
     * @return the value of csc_task.plan_end_time
     *
     * @mbggenerated
     */
    public Date getPlanEndTime() {
        return planEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.plan_end_time
     *
     * @param planEndTime the value for csc_task.plan_end_time
     *
     * @mbggenerated
     */
    public void setPlanEndTime(Date planEndTime) {
        this.planEndTime = planEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.task_start_time
     *
     * @return the value of csc_task.task_start_time
     *
     * @mbggenerated
     */
    public Date getTaskStartTime() {
        return taskStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.task_start_time
     *
     * @param taskStartTime the value for csc_task.task_start_time
     *
     * @mbggenerated
     */
    public void setTaskStartTime(Date taskStartTime) {
        this.taskStartTime = taskStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.task_end_time
     *
     * @return the value of csc_task.task_end_time
     *
     * @mbggenerated
     */
    public Date getTaskEndTime() {
        return taskEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.task_end_time
     *
     * @param taskEndTime the value for csc_task.task_end_time
     *
     * @mbggenerated
     */
    public void setTaskEndTime(Date taskEndTime) {
        this.taskEndTime = taskEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.is_plan
     *
     * @return the value of csc_task.is_plan
     *
     * @mbggenerated
     */
    public Boolean getIsPlan() {
        return isPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.is_plan
     *
     * @param isPlan the value for csc_task.is_plan
     *
     * @mbggenerated
     */
    public void setIsPlan(Boolean isPlan) {
        this.isPlan = isPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.set_time
     *
     * @return the value of csc_task.set_time
     *
     * @mbggenerated
     */
    public Integer getSetTime() {
        return setTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.set_time
     *
     * @param setTime the value for csc_task.set_time
     *
     * @mbggenerated
     */
    public void setSetTime(Integer setTime) {
        this.setTime = setTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.real_time
     *
     * @return the value of csc_task.real_time
     *
     * @mbggenerated
     */
    public Integer getRealTime() {
        return realTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.real_time
     *
     * @param realTime the value for csc_task.real_time
     *
     * @mbggenerated
     */
    public void setRealTime(Integer realTime) {
        this.realTime = realTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.task_status
     *
     * @return the value of csc_task.task_status
     *
     * @mbggenerated
     */
    public String getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.task_status
     *
     * @param taskStatus the value for csc_task.task_status
     *
     * @mbggenerated
     */
    public void setTaskStatus(String taskStatus) {
        this.taskStatus = taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.post
     *
     * @return the value of csc_task.post
     *
     * @mbggenerated
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.post
     *
     * @param post the value for csc_task.post
     *
     * @mbggenerated
     */
    public void setPost(String post) {
        this.post = post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.person_id
     *
     * @return the value of csc_task.person_id
     *
     * @mbggenerated
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.person_id
     *
     * @param personId the value for csc_task.person_id
     *
     * @mbggenerated
     */
    public void setPersonId(String personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.person_name
     *
     * @return the value of csc_task.person_name
     *
     * @mbggenerated
     */
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.person_name
     *
     * @param personName the value for csc_task.person_name
     *
     * @mbggenerated
     */
    public void setPersonName(String personName) {
        this.personName = personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.task_per_name
     *
     * @return the value of csc_task.task_per_name
     *
     * @mbggenerated
     */
    public String getTaskPerName() {
        return taskPerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.task_per_name
     *
     * @param taskPerName the value for csc_task.task_per_name
     *
     * @mbggenerated
     */
    public void setTaskPerName(String taskPerName) {
        this.taskPerName = taskPerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.upload_per_id
     *
     * @return the value of csc_task.upload_per_id
     *
     * @mbggenerated
     */
    public Long getUploadPerId() {
        return uploadPerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.upload_per_id
     *
     * @param uploadPerId the value for csc_task.upload_per_id
     *
     * @mbggenerated
     */
    public void setUploadPerId(Long uploadPerId) {
        this.uploadPerId = uploadPerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.upload_per_name
     *
     * @return the value of csc_task.upload_per_name
     *
     * @mbggenerated
     */
    public String getUploadPerName() {
        return uploadPerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.upload_per_name
     *
     * @param uploadPerName the value for csc_task.upload_per_name
     *
     * @mbggenerated
     */
    public void setUploadPerName(String uploadPerName) {
        this.uploadPerName = uploadPerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.upload_time
     *
     * @return the value of csc_task.upload_time
     *
     * @mbggenerated
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.upload_time
     *
     * @param uploadTime the value for csc_task.upload_time
     *
     * @mbggenerated
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.upload_phone
     *
     * @return the value of csc_task.upload_phone
     *
     * @mbggenerated
     */
    public String getUploadPhone() {
        return uploadPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.upload_phone
     *
     * @param uploadPhone the value for csc_task.upload_phone
     *
     * @mbggenerated
     */
    public void setUploadPhone(String uploadPhone) {
        this.uploadPhone = uploadPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.line_id
     *
     * @return the value of csc_task.line_id
     *
     * @mbggenerated
     */
    public Long getLineId() {
        return lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.line_id
     *
     * @param lineId the value for csc_task.line_id
     *
     * @mbggenerated
     */
    public void setLineId(Long lineId) {
        this.lineId = lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.line_name
     *
     * @return the value of csc_task.line_name
     *
     * @mbggenerated
     */
    public String getLineName() {
        return lineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.line_name
     *
     * @param lineName the value for csc_task.line_name
     *
     * @mbggenerated
     */
    public void setLineName(String lineName) {
        this.lineName = lineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.class_id
     *
     * @return the value of csc_task.class_id
     *
     * @mbggenerated
     */
    public Long getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.class_id
     *
     * @param classId the value for csc_task.class_id
     *
     * @mbggenerated
     */
    public void setClassId(Long classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.class_name
     *
     * @return the value of csc_task.class_name
     *
     * @mbggenerated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.class_name
     *
     * @param className the value for csc_task.class_name
     *
     * @mbggenerated
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.round_id
     *
     * @return the value of csc_task.round_id
     *
     * @mbggenerated
     */
    public Long getRoundId() {
        return roundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.round_id
     *
     * @param roundId the value for csc_task.round_id
     *
     * @mbggenerated
     */
    public void setRoundId(Long roundId) {
        this.roundId = roundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.round_name
     *
     * @return the value of csc_task.round_name
     *
     * @mbggenerated
     */
    public String getRoundName() {
        return roundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.round_name
     *
     * @param roundName the value for csc_task.round_name
     *
     * @mbggenerated
     */
    public void setRoundName(String roundName) {
        this.roundName = roundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.last_task_id
     *
     * @return the value of csc_task.last_task_id
     *
     * @mbggenerated
     */
    public Long getLastTaskId() {
        return lastTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.last_task_id
     *
     * @param lastTaskId the value for csc_task.last_task_id
     *
     * @mbggenerated
     */
    public void setLastTaskId(Long lastTaskId) {
        this.lastTaskId = lastTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.task_type
     *
     * @return the value of csc_task.task_type
     *
     * @mbggenerated
     */
    public String getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.task_type
     *
     * @param taskType the value for csc_task.task_type
     *
     * @mbggenerated
     */
    public void setTaskType(String taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.org_id
     *
     * @return the value of csc_task.org_id
     *
     * @mbggenerated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.org_id
     *
     * @param orgId the value for csc_task.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.org_name
     *
     * @return the value of csc_task.org_name
     *
     * @mbggenerated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.org_name
     *
     * @param orgName the value for csc_task.org_name
     *
     * @mbggenerated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.created_dt
     *
     * @return the value of csc_task.created_dt
     *
     * @mbggenerated
     */
    public Date getCreatedDt() {
        return createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.created_dt
     *
     * @param createdDt the value for csc_task.created_dt
     *
     * @mbggenerated
     */
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.created_by
     *
     * @return the value of csc_task.created_by
     *
     * @mbggenerated
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.created_by
     *
     * @param createdBy the value for csc_task.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.updated_by
     *
     * @return the value of csc_task.updated_by
     *
     * @mbggenerated
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.updated_by
     *
     * @param updatedBy the value for csc_task.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.updated_dt
     *
     * @return the value of csc_task.updated_dt
     *
     * @mbggenerated
     */
    public Date getUpdatedDt() {
        return updatedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.updated_dt
     *
     * @param updatedDt the value for csc_task.updated_dt
     *
     * @mbggenerated
     */
    public void setUpdatedDt(Date updatedDt) {
        this.updatedDt = updatedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.created_by_name
     *
     * @return the value of csc_task.created_by_name
     *
     * @mbggenerated
     */
    public String getCreatedByName() {
        return createdByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.created_by_name
     *
     * @param createdByName the value for csc_task.created_by_name
     *
     * @mbggenerated
     */
    public void setCreatedByName(String createdByName) {
        this.createdByName = createdByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.updated_by_name
     *
     * @return the value of csc_task.updated_by_name
     *
     * @mbggenerated
     */
    public String getUpdatedByName() {
        return updatedByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.updated_by_name
     *
     * @param updatedByName the value for csc_task.updated_by_name
     *
     * @mbggenerated
     */
    public void setUpdatedByName(String updatedByName) {
        this.updatedByName = updatedByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.tenantid
     *
     * @return the value of csc_task.tenantid
     *
     * @mbggenerated
     */
    public Long getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.tenantid
     *
     * @param tenantid the value for csc_task.tenantid
     *
     * @mbggenerated
     */
    public void setTenantid(Long tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.ver
     *
     * @return the value of csc_task.ver
     *
     * @mbggenerated
     */
    public Integer getVer() {
        return ver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.ver
     *
     * @param ver the value for csc_task.ver
     *
     * @mbggenerated
     */
    public void setVer(Integer ver) {
        this.ver = ver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.is_bluetooth_collect
     *
     * @return the value of csc_task.is_bluetooth_collect
     *
     * @mbggenerated
     */
    public Boolean getIsBluetoothCollect() {
        return isBluetoothCollect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.is_bluetooth_collect
     *
     * @param isBluetoothCollect the value for csc_task.is_bluetooth_collect
     *
     * @mbggenerated
     */
    public void setIsBluetoothCollect(Boolean isBluetoothCollect) {
        this.isBluetoothCollect = isBluetoothCollect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.post_id
     *
     * @return the value of csc_task.post_id
     *
     * @mbggenerated
     */
    public Long getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.post_id
     *
     * @param postId the value for csc_task.post_id
     *
     * @mbggenerated
     */
    public void setPostId(Long postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.post_name
     *
     * @return the value of csc_task.post_name
     *
     * @mbggenerated
     */
    public String getPostName() {
        return postName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.post_name
     *
     * @param postName the value for csc_task.post_name
     *
     * @mbggenerated
     */
    public void setPostName(String postName) {
        this.postName = postName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.sign_method
     *
     * @return the value of csc_task.sign_method
     *
     * @mbggenerated
     */
    public String getSignMethod() {
        return signMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.sign_method
     *
     * @param signMethod the value for csc_task.sign_method
     *
     * @mbggenerated
     */
    public void setSignMethod(String signMethod) {
        this.signMethod = signMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.person_nfccard
     *
     * @return the value of csc_task.person_nfccard
     *
     * @mbggenerated
     */
    public String getPersonNfccard() {
        return personNfccard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.person_nfccard
     *
     * @param personNfccard the value for csc_task.person_nfccard
     *
     * @mbggenerated
     */
    public void setPersonNfccard(String personNfccard) {
        this.personNfccard = personNfccard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.step_number
     *
     * @return the value of csc_task.step_number
     *
     * @mbggenerated
     */
    public Integer getStepNumber() {
        return stepNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.step_number
     *
     * @param stepNumber the value for csc_task.step_number
     *
     * @mbggenerated
     */
    public void setStepNumber(Integer stepNumber) {
        this.stepNumber = stepNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.stopcheck_state
     *
     * @return the value of csc_task.stopcheck_state
     *
     * @mbggenerated
     */
    public String getStopcheckState() {
        return stopcheckState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.stopcheck_state
     *
     * @param stopcheckState the value for csc_task.stopcheck_state
     *
     * @mbggenerated
     */
    public void setStopcheckState(String stopcheckState) {
        this.stopcheckState = stopcheckState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.org_code
     *
     * @return the value of csc_task.org_code
     *
     * @mbggenerated
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.org_code
     *
     * @param orgCode the value for csc_task.org_code
     *
     * @mbggenerated
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.download_status
     *
     * @return the value of csc_task.download_status
     *
     * @mbggenerated
     */
    public Byte getDownloadStatus() {
        return downloadStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.download_status
     *
     * @param downloadStatus the value for csc_task.download_status
     *
     * @mbggenerated
     */
    public void setDownloadStatus(Byte downloadStatus) {
        this.downloadStatus = downloadStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.duration_control
     *
     * @return the value of csc_task.duration_control
     *
     * @mbggenerated
     */
    public Boolean getDurationControl() {
        return durationControl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.duration_control
     *
     * @param durationControl the value for csc_task.duration_control
     *
     * @mbggenerated
     */
    public void setDurationControl(Boolean durationControl) {
        this.durationControl = durationControl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.time_range
     *
     * @return the value of csc_task.time_range
     *
     * @mbggenerated
     */
    public String getTimeRange() {
        return timeRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.time_range
     *
     * @param timeRange the value for csc_task.time_range
     *
     * @mbggenerated
     */
    public void setTimeRange(String timeRange) {
        this.timeRange = timeRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.is_auto_arrive
     *
     * @return the value of csc_task.is_auto_arrive
     *
     * @mbggenerated
     */
    public Boolean getIsAutoArrive() {
        return isAutoArrive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.is_auto_arrive
     *
     * @param isAutoArrive the value for csc_task.is_auto_arrive
     *
     * @mbggenerated
     */
    public void setIsAutoArrive(Boolean isAutoArrive) {
        this.isAutoArrive = isAutoArrive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.is_jump_station
     *
     * @return the value of csc_task.is_jump_station
     *
     * @mbggenerated
     */
    public Boolean getIsJumpStation() {
        return isJumpStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.is_jump_station
     *
     * @param isJumpStation the value for csc_task.is_jump_station
     *
     * @mbggenerated
     */
    public void setIsJumpStation(Boolean isJumpStation) {
        this.isJumpStation = isJumpStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.force_photo
     *
     * @return the value of csc_task.force_photo
     *
     * @mbggenerated
     */
    public Boolean getForcePhoto() {
        return forcePhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.force_photo
     *
     * @param forcePhoto the value for csc_task.force_photo
     *
     * @mbggenerated
     */
    public void setForcePhoto(Boolean forcePhoto) {
        this.forcePhoto = forcePhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.is_punctual
     *
     * @return the value of csc_task.is_punctual
     *
     * @mbggenerated
     */
    public Boolean getIsPunctual() {
        return isPunctual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.is_punctual
     *
     * @param isPunctual the value for csc_task.is_punctual
     *
     * @mbggenerated
     */
    public void setIsPunctual(Boolean isPunctual) {
        this.isPunctual = isPunctual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.charger_id
     *
     * @return the value of csc_task.charger_id
     *
     * @mbggenerated
     */
    public String getChargerId() {
        return chargerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.charger_id
     *
     * @param chargerId the value for csc_task.charger_id
     *
     * @mbggenerated
     */
    public void setChargerId(String chargerId) {
        this.chargerId = chargerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.charger_name
     *
     * @return the value of csc_task.charger_name
     *
     * @mbggenerated
     */
    public String getChargerName() {
        return chargerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.charger_name
     *
     * @param chargerName the value for csc_task.charger_name
     *
     * @mbggenerated
     */
    public void setChargerName(String chargerName) {
        this.chargerName = chargerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.is_controltime
     *
     * @return the value of csc_task.is_controltime
     *
     * @mbggenerated
     */
    public Integer getIsControltime() {
        return isControltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.is_controltime
     *
     * @param isControltime the value for csc_task.is_controltime
     *
     * @mbggenerated
     */
    public void setIsControltime(Integer isControltime) {
        this.isControltime = isControltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.is_many_per
     *
     * @return the value of csc_task.is_many_per
     *
     * @mbggenerated
     */
    public Integer getIsManyPer() {
        return isManyPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.is_many_per
     *
     * @param isManyPer the value for csc_task.is_many_per
     *
     * @mbggenerated
     */
    public void setIsManyPer(Integer isManyPer) {
        this.isManyPer = isManyPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task.df
     *
     * @return the value of csc_task.df
     *
     * @mbggenerated
     */
    public Boolean getDf() {
        return df;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task.df
     *
     * @param df the value for csc_task.df
     *
     * @mbggenerated
     */
    public void setDf(Boolean df) {
        this.df = df;
    }
}