package com.hy.mapper;

import com.hy.entity.Messageflow;

public interface MessageflowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageflow
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageflow
     *
     * @mbggenerated
     */
    int insert(Messageflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageflow
     *
     * @mbggenerated
     */
    int insertSelective(Messageflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageflow
     *
     * @mbggenerated
     */
    Messageflow selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageflow
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Messageflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageflow
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Messageflow record);
}