package com.hy.dao;

import com.hy.entity.Catalog;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface CatalogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbggenerated
     */
    int insert(Catalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbggenerated
     */
    int insertSelective(Catalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbggenerated
     */
    Catalog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Catalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Catalog record);

    List<Catalog> selectAll();

    @Update("update catalog set sold=sold+#{num} where id=#{id} and sold+#{num} <=total")
    int updateCatalognum(@Param("id") Integer id, @Param("num") Integer num);


}