package com.hy.entity;

import com.hy.entity.base.BaseEntity;
import java.util.Date;

public class Messageflow extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messageflow.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messageflow.money
     *
     * @mbggenerated
     */
    private Long money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messageflow.payUserid
     *
     * @mbggenerated
     */
    private String payuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messageflow.receiveUserid
     *
     * @mbggenerated
     */
    private String receiveuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messageflow.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messageflow.createdate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messageflow.updatedate
     *
     * @mbggenerated
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messageflow.id
     *
     * @return the value of messageflow.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messageflow.id
     *
     * @param id the value for messageflow.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messageflow.money
     *
     * @return the value of messageflow.money
     *
     * @mbggenerated
     */
    public Long getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messageflow.money
     *
     * @param money the value for messageflow.money
     *
     * @mbggenerated
     */
    public void setMoney(Long money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messageflow.payUserid
     *
     * @return the value of messageflow.payUserid
     *
     * @mbggenerated
     */
    public String getPayuserid() {
        return payuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messageflow.payUserid
     *
     * @param payuserid the value for messageflow.payUserid
     *
     * @mbggenerated
     */
    public void setPayuserid(String payuserid) {
        this.payuserid = payuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messageflow.receiveUserid
     *
     * @return the value of messageflow.receiveUserid
     *
     * @mbggenerated
     */
    public String getReceiveuserid() {
        return receiveuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messageflow.receiveUserid
     *
     * @param receiveuserid the value for messageflow.receiveUserid
     *
     * @mbggenerated
     */
    public void setReceiveuserid(String receiveuserid) {
        this.receiveuserid = receiveuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messageflow.status
     *
     * @return the value of messageflow.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messageflow.status
     *
     * @param status the value for messageflow.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messageflow.createdate
     *
     * @return the value of messageflow.createdate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messageflow.createdate
     *
     * @param createdate the value for messageflow.createdate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messageflow.updatedate
     *
     * @return the value of messageflow.updatedate
     *
     * @mbggenerated
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messageflow.updatedate
     *
     * @param updatedate the value for messageflow.updatedate
     *
     * @mbggenerated
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}