package com.hy.mybatis.entity;

import com.hy.mybatis.entity.base.BaseEntity;
import java.math.BigDecimal;
import java.util.Date;

public class CscTaskItem extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.task_item_id
     *
     * @mbggenerated
     */
    private Long taskItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.task_station_id
     *
     * @mbggenerated
     */
    private Long taskStationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.task_id
     *
     * @mbggenerated
     */
    private Long taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.task_code
     *
     * @mbggenerated
     */
    private String taskCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.task_name
     *
     * @mbggenerated
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.line_id
     *
     * @mbggenerated
     */
    private Long lineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.line_name
     *
     * @mbggenerated
     */
    private String lineName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.station_id
     *
     * @mbggenerated
     */
    private Long stationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.station_name
     *
     * @mbggenerated
     */
    private String stationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.item_id
     *
     * @mbggenerated
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.item_name
     *
     * @mbggenerated
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.item_type
     *
     * @mbggenerated
     */
    private String itemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.item_remark
     *
     * @mbggenerated
     */
    private String itemRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.check_obj_type
     *
     * @mbggenerated
     */
    private String checkObjType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.eq_id
     *
     * @mbggenerated
     */
    private Long eqId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.eq_name
     *
     * @mbggenerated
     */
    private String eqName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.unit_id
     *
     * @mbggenerated
     */
    private Long unitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.unit_symbol
     *
     * @mbggenerated
     */
    private String unitSymbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.item_index_name
     *
     * @mbggenerated
     */
    private String itemIndexName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.org_name
     *
     * @mbggenerated
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.org_id
     *
     * @mbggenerated
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.check_value
     *
     * @mbggenerated
     */
    private BigDecimal checkValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.standard_value
     *
     * @mbggenerated
     */
    private BigDecimal standardValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.upper_limit_value
     *
     * @mbggenerated
     */
    private BigDecimal upperLimitValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.lower_limit_value
     *
     * @mbggenerated
     */
    private BigDecimal lowerLimitValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.ulti_up_limit_value
     *
     * @mbggenerated
     */
    private BigDecimal ultiUpLimitValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.ulti_low_limit_value
     *
     * @mbggenerated
     */
    private BigDecimal ultiLowLimitValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.seq
     *
     * @mbggenerated
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.check_result
     *
     * @mbggenerated
     */
    private String checkResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.check_last_value
     *
     * @mbggenerated
     */
    private BigDecimal checkLastValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.last_task_id
     *
     * @mbggenerated
     */
    private Long lastTaskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.check_result_last
     *
     * @mbggenerated
     */
    private String checkResultLast;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.check_per_id
     *
     * @mbggenerated
     */
    private Long checkPerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.check_per_name
     *
     * @mbggenerated
     */
    private String checkPerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.check_time
     *
     * @mbggenerated
     */
    private Date checkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.upload_time
     *
     * @mbggenerated
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.upload_per_id
     *
     * @mbggenerated
     */
    private Long uploadPerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.upload_per_name
     *
     * @mbggenerated
     */
    private String uploadPerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.upload_phone
     *
     * @mbggenerated
     */
    private String uploadPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.check_gps_x
     *
     * @mbggenerated
     */
    private BigDecimal checkGpsX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.check_gps_y
     *
     * @mbggenerated
     */
    private BigDecimal checkGpsY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.created_dt
     *
     * @mbggenerated
     */
    private Date createdDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.created_by
     *
     * @mbggenerated
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.updated_by
     *
     * @mbggenerated
     */
    private Long updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.updated_dt
     *
     * @mbggenerated
     */
    private Date updatedDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.created_by_name
     *
     * @mbggenerated
     */
    private String createdByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.updated_by_name
     *
     * @mbggenerated
     */
    private String updatedByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.tenantid
     *
     * @mbggenerated
     */
    private Long tenantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.ver
     *
     * @mbggenerated
     */
    private Integer ver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.eq_is_not_work
     *
     * @mbggenerated
     */
    private Boolean eqIsNotWork;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.eq_status
     *
     * @mbggenerated
     */
    private String eqStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.task_item_img
     *
     * @mbggenerated
     */
    private String taskItemImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.lj_remark
     *
     * @mbggenerated
     */
    private String ljRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.remark_user
     *
     * @mbggenerated
     */
    private Long remarkUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.remark_time
     *
     * @mbggenerated
     */
    private Date remarkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.remark_username
     *
     * @mbggenerated
     */
    private String remarkUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_item.df
     *
     * @mbggenerated
     */
    private Boolean df;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.task_item_id
     *
     * @return the value of csc_task_item.task_item_id
     *
     * @mbggenerated
     */
    public Long getTaskItemId() {
        return taskItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.task_item_id
     *
     * @param taskItemId the value for csc_task_item.task_item_id
     *
     * @mbggenerated
     */
    public void setTaskItemId(Long taskItemId) {
        this.taskItemId = taskItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.task_station_id
     *
     * @return the value of csc_task_item.task_station_id
     *
     * @mbggenerated
     */
    public Long getTaskStationId() {
        return taskStationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.task_station_id
     *
     * @param taskStationId the value for csc_task_item.task_station_id
     *
     * @mbggenerated
     */
    public void setTaskStationId(Long taskStationId) {
        this.taskStationId = taskStationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.task_id
     *
     * @return the value of csc_task_item.task_id
     *
     * @mbggenerated
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.task_id
     *
     * @param taskId the value for csc_task_item.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.task_code
     *
     * @return the value of csc_task_item.task_code
     *
     * @mbggenerated
     */
    public String getTaskCode() {
        return taskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.task_code
     *
     * @param taskCode the value for csc_task_item.task_code
     *
     * @mbggenerated
     */
    public void setTaskCode(String taskCode) {
        this.taskCode = taskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.task_name
     *
     * @return the value of csc_task_item.task_name
     *
     * @mbggenerated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.task_name
     *
     * @param taskName the value for csc_task_item.task_name
     *
     * @mbggenerated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.line_id
     *
     * @return the value of csc_task_item.line_id
     *
     * @mbggenerated
     */
    public Long getLineId() {
        return lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.line_id
     *
     * @param lineId the value for csc_task_item.line_id
     *
     * @mbggenerated
     */
    public void setLineId(Long lineId) {
        this.lineId = lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.line_name
     *
     * @return the value of csc_task_item.line_name
     *
     * @mbggenerated
     */
    public String getLineName() {
        return lineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.line_name
     *
     * @param lineName the value for csc_task_item.line_name
     *
     * @mbggenerated
     */
    public void setLineName(String lineName) {
        this.lineName = lineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.station_id
     *
     * @return the value of csc_task_item.station_id
     *
     * @mbggenerated
     */
    public Long getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.station_id
     *
     * @param stationId the value for csc_task_item.station_id
     *
     * @mbggenerated
     */
    public void setStationId(Long stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.station_name
     *
     * @return the value of csc_task_item.station_name
     *
     * @mbggenerated
     */
    public String getStationName() {
        return stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.station_name
     *
     * @param stationName the value for csc_task_item.station_name
     *
     * @mbggenerated
     */
    public void setStationName(String stationName) {
        this.stationName = stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.item_id
     *
     * @return the value of csc_task_item.item_id
     *
     * @mbggenerated
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.item_id
     *
     * @param itemId the value for csc_task_item.item_id
     *
     * @mbggenerated
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.item_name
     *
     * @return the value of csc_task_item.item_name
     *
     * @mbggenerated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.item_name
     *
     * @param itemName the value for csc_task_item.item_name
     *
     * @mbggenerated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.item_type
     *
     * @return the value of csc_task_item.item_type
     *
     * @mbggenerated
     */
    public String getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.item_type
     *
     * @param itemType the value for csc_task_item.item_type
     *
     * @mbggenerated
     */
    public void setItemType(String itemType) {
        this.itemType = itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.item_remark
     *
     * @return the value of csc_task_item.item_remark
     *
     * @mbggenerated
     */
    public String getItemRemark() {
        return itemRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.item_remark
     *
     * @param itemRemark the value for csc_task_item.item_remark
     *
     * @mbggenerated
     */
    public void setItemRemark(String itemRemark) {
        this.itemRemark = itemRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.check_obj_type
     *
     * @return the value of csc_task_item.check_obj_type
     *
     * @mbggenerated
     */
    public String getCheckObjType() {
        return checkObjType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.check_obj_type
     *
     * @param checkObjType the value for csc_task_item.check_obj_type
     *
     * @mbggenerated
     */
    public void setCheckObjType(String checkObjType) {
        this.checkObjType = checkObjType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.eq_id
     *
     * @return the value of csc_task_item.eq_id
     *
     * @mbggenerated
     */
    public Long getEqId() {
        return eqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.eq_id
     *
     * @param eqId the value for csc_task_item.eq_id
     *
     * @mbggenerated
     */
    public void setEqId(Long eqId) {
        this.eqId = eqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.eq_name
     *
     * @return the value of csc_task_item.eq_name
     *
     * @mbggenerated
     */
    public String getEqName() {
        return eqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.eq_name
     *
     * @param eqName the value for csc_task_item.eq_name
     *
     * @mbggenerated
     */
    public void setEqName(String eqName) {
        this.eqName = eqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.unit_id
     *
     * @return the value of csc_task_item.unit_id
     *
     * @mbggenerated
     */
    public Long getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.unit_id
     *
     * @param unitId the value for csc_task_item.unit_id
     *
     * @mbggenerated
     */
    public void setUnitId(Long unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.unit_symbol
     *
     * @return the value of csc_task_item.unit_symbol
     *
     * @mbggenerated
     */
    public String getUnitSymbol() {
        return unitSymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.unit_symbol
     *
     * @param unitSymbol the value for csc_task_item.unit_symbol
     *
     * @mbggenerated
     */
    public void setUnitSymbol(String unitSymbol) {
        this.unitSymbol = unitSymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.item_index_name
     *
     * @return the value of csc_task_item.item_index_name
     *
     * @mbggenerated
     */
    public String getItemIndexName() {
        return itemIndexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.item_index_name
     *
     * @param itemIndexName the value for csc_task_item.item_index_name
     *
     * @mbggenerated
     */
    public void setItemIndexName(String itemIndexName) {
        this.itemIndexName = itemIndexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.org_name
     *
     * @return the value of csc_task_item.org_name
     *
     * @mbggenerated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.org_name
     *
     * @param orgName the value for csc_task_item.org_name
     *
     * @mbggenerated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.org_id
     *
     * @return the value of csc_task_item.org_id
     *
     * @mbggenerated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.org_id
     *
     * @param orgId the value for csc_task_item.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.check_value
     *
     * @return the value of csc_task_item.check_value
     *
     * @mbggenerated
     */
    public BigDecimal getCheckValue() {
        return checkValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.check_value
     *
     * @param checkValue the value for csc_task_item.check_value
     *
     * @mbggenerated
     */
    public void setCheckValue(BigDecimal checkValue) {
        this.checkValue = checkValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.standard_value
     *
     * @return the value of csc_task_item.standard_value
     *
     * @mbggenerated
     */
    public BigDecimal getStandardValue() {
        return standardValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.standard_value
     *
     * @param standardValue the value for csc_task_item.standard_value
     *
     * @mbggenerated
     */
    public void setStandardValue(BigDecimal standardValue) {
        this.standardValue = standardValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.upper_limit_value
     *
     * @return the value of csc_task_item.upper_limit_value
     *
     * @mbggenerated
     */
    public BigDecimal getUpperLimitValue() {
        return upperLimitValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.upper_limit_value
     *
     * @param upperLimitValue the value for csc_task_item.upper_limit_value
     *
     * @mbggenerated
     */
    public void setUpperLimitValue(BigDecimal upperLimitValue) {
        this.upperLimitValue = upperLimitValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.lower_limit_value
     *
     * @return the value of csc_task_item.lower_limit_value
     *
     * @mbggenerated
     */
    public BigDecimal getLowerLimitValue() {
        return lowerLimitValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.lower_limit_value
     *
     * @param lowerLimitValue the value for csc_task_item.lower_limit_value
     *
     * @mbggenerated
     */
    public void setLowerLimitValue(BigDecimal lowerLimitValue) {
        this.lowerLimitValue = lowerLimitValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.ulti_up_limit_value
     *
     * @return the value of csc_task_item.ulti_up_limit_value
     *
     * @mbggenerated
     */
    public BigDecimal getUltiUpLimitValue() {
        return ultiUpLimitValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.ulti_up_limit_value
     *
     * @param ultiUpLimitValue the value for csc_task_item.ulti_up_limit_value
     *
     * @mbggenerated
     */
    public void setUltiUpLimitValue(BigDecimal ultiUpLimitValue) {
        this.ultiUpLimitValue = ultiUpLimitValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.ulti_low_limit_value
     *
     * @return the value of csc_task_item.ulti_low_limit_value
     *
     * @mbggenerated
     */
    public BigDecimal getUltiLowLimitValue() {
        return ultiLowLimitValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.ulti_low_limit_value
     *
     * @param ultiLowLimitValue the value for csc_task_item.ulti_low_limit_value
     *
     * @mbggenerated
     */
    public void setUltiLowLimitValue(BigDecimal ultiLowLimitValue) {
        this.ultiLowLimitValue = ultiLowLimitValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.seq
     *
     * @return the value of csc_task_item.seq
     *
     * @mbggenerated
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.seq
     *
     * @param seq the value for csc_task_item.seq
     *
     * @mbggenerated
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.check_result
     *
     * @return the value of csc_task_item.check_result
     *
     * @mbggenerated
     */
    public String getCheckResult() {
        return checkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.check_result
     *
     * @param checkResult the value for csc_task_item.check_result
     *
     * @mbggenerated
     */
    public void setCheckResult(String checkResult) {
        this.checkResult = checkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.check_last_value
     *
     * @return the value of csc_task_item.check_last_value
     *
     * @mbggenerated
     */
    public BigDecimal getCheckLastValue() {
        return checkLastValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.check_last_value
     *
     * @param checkLastValue the value for csc_task_item.check_last_value
     *
     * @mbggenerated
     */
    public void setCheckLastValue(BigDecimal checkLastValue) {
        this.checkLastValue = checkLastValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.last_task_id
     *
     * @return the value of csc_task_item.last_task_id
     *
     * @mbggenerated
     */
    public Long getLastTaskId() {
        return lastTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.last_task_id
     *
     * @param lastTaskId the value for csc_task_item.last_task_id
     *
     * @mbggenerated
     */
    public void setLastTaskId(Long lastTaskId) {
        this.lastTaskId = lastTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.check_result_last
     *
     * @return the value of csc_task_item.check_result_last
     *
     * @mbggenerated
     */
    public String getCheckResultLast() {
        return checkResultLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.check_result_last
     *
     * @param checkResultLast the value for csc_task_item.check_result_last
     *
     * @mbggenerated
     */
    public void setCheckResultLast(String checkResultLast) {
        this.checkResultLast = checkResultLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.remark
     *
     * @return the value of csc_task_item.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.remark
     *
     * @param remark the value for csc_task_item.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.check_per_id
     *
     * @return the value of csc_task_item.check_per_id
     *
     * @mbggenerated
     */
    public Long getCheckPerId() {
        return checkPerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.check_per_id
     *
     * @param checkPerId the value for csc_task_item.check_per_id
     *
     * @mbggenerated
     */
    public void setCheckPerId(Long checkPerId) {
        this.checkPerId = checkPerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.check_per_name
     *
     * @return the value of csc_task_item.check_per_name
     *
     * @mbggenerated
     */
    public String getCheckPerName() {
        return checkPerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.check_per_name
     *
     * @param checkPerName the value for csc_task_item.check_per_name
     *
     * @mbggenerated
     */
    public void setCheckPerName(String checkPerName) {
        this.checkPerName = checkPerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.check_time
     *
     * @return the value of csc_task_item.check_time
     *
     * @mbggenerated
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.check_time
     *
     * @param checkTime the value for csc_task_item.check_time
     *
     * @mbggenerated
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.upload_time
     *
     * @return the value of csc_task_item.upload_time
     *
     * @mbggenerated
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.upload_time
     *
     * @param uploadTime the value for csc_task_item.upload_time
     *
     * @mbggenerated
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.upload_per_id
     *
     * @return the value of csc_task_item.upload_per_id
     *
     * @mbggenerated
     */
    public Long getUploadPerId() {
        return uploadPerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.upload_per_id
     *
     * @param uploadPerId the value for csc_task_item.upload_per_id
     *
     * @mbggenerated
     */
    public void setUploadPerId(Long uploadPerId) {
        this.uploadPerId = uploadPerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.upload_per_name
     *
     * @return the value of csc_task_item.upload_per_name
     *
     * @mbggenerated
     */
    public String getUploadPerName() {
        return uploadPerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.upload_per_name
     *
     * @param uploadPerName the value for csc_task_item.upload_per_name
     *
     * @mbggenerated
     */
    public void setUploadPerName(String uploadPerName) {
        this.uploadPerName = uploadPerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.upload_phone
     *
     * @return the value of csc_task_item.upload_phone
     *
     * @mbggenerated
     */
    public String getUploadPhone() {
        return uploadPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.upload_phone
     *
     * @param uploadPhone the value for csc_task_item.upload_phone
     *
     * @mbggenerated
     */
    public void setUploadPhone(String uploadPhone) {
        this.uploadPhone = uploadPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.check_gps_x
     *
     * @return the value of csc_task_item.check_gps_x
     *
     * @mbggenerated
     */
    public BigDecimal getCheckGpsX() {
        return checkGpsX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.check_gps_x
     *
     * @param checkGpsX the value for csc_task_item.check_gps_x
     *
     * @mbggenerated
     */
    public void setCheckGpsX(BigDecimal checkGpsX) {
        this.checkGpsX = checkGpsX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.check_gps_y
     *
     * @return the value of csc_task_item.check_gps_y
     *
     * @mbggenerated
     */
    public BigDecimal getCheckGpsY() {
        return checkGpsY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.check_gps_y
     *
     * @param checkGpsY the value for csc_task_item.check_gps_y
     *
     * @mbggenerated
     */
    public void setCheckGpsY(BigDecimal checkGpsY) {
        this.checkGpsY = checkGpsY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.created_dt
     *
     * @return the value of csc_task_item.created_dt
     *
     * @mbggenerated
     */
    public Date getCreatedDt() {
        return createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.created_dt
     *
     * @param createdDt the value for csc_task_item.created_dt
     *
     * @mbggenerated
     */
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.created_by
     *
     * @return the value of csc_task_item.created_by
     *
     * @mbggenerated
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.created_by
     *
     * @param createdBy the value for csc_task_item.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.updated_by
     *
     * @return the value of csc_task_item.updated_by
     *
     * @mbggenerated
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.updated_by
     *
     * @param updatedBy the value for csc_task_item.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.updated_dt
     *
     * @return the value of csc_task_item.updated_dt
     *
     * @mbggenerated
     */
    public Date getUpdatedDt() {
        return updatedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.updated_dt
     *
     * @param updatedDt the value for csc_task_item.updated_dt
     *
     * @mbggenerated
     */
    public void setUpdatedDt(Date updatedDt) {
        this.updatedDt = updatedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.created_by_name
     *
     * @return the value of csc_task_item.created_by_name
     *
     * @mbggenerated
     */
    public String getCreatedByName() {
        return createdByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.created_by_name
     *
     * @param createdByName the value for csc_task_item.created_by_name
     *
     * @mbggenerated
     */
    public void setCreatedByName(String createdByName) {
        this.createdByName = createdByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.updated_by_name
     *
     * @return the value of csc_task_item.updated_by_name
     *
     * @mbggenerated
     */
    public String getUpdatedByName() {
        return updatedByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.updated_by_name
     *
     * @param updatedByName the value for csc_task_item.updated_by_name
     *
     * @mbggenerated
     */
    public void setUpdatedByName(String updatedByName) {
        this.updatedByName = updatedByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.tenantid
     *
     * @return the value of csc_task_item.tenantid
     *
     * @mbggenerated
     */
    public Long getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.tenantid
     *
     * @param tenantid the value for csc_task_item.tenantid
     *
     * @mbggenerated
     */
    public void setTenantid(Long tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.ver
     *
     * @return the value of csc_task_item.ver
     *
     * @mbggenerated
     */
    public Integer getVer() {
        return ver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.ver
     *
     * @param ver the value for csc_task_item.ver
     *
     * @mbggenerated
     */
    public void setVer(Integer ver) {
        this.ver = ver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.eq_is_not_work
     *
     * @return the value of csc_task_item.eq_is_not_work
     *
     * @mbggenerated
     */
    public Boolean getEqIsNotWork() {
        return eqIsNotWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.eq_is_not_work
     *
     * @param eqIsNotWork the value for csc_task_item.eq_is_not_work
     *
     * @mbggenerated
     */
    public void setEqIsNotWork(Boolean eqIsNotWork) {
        this.eqIsNotWork = eqIsNotWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.eq_status
     *
     * @return the value of csc_task_item.eq_status
     *
     * @mbggenerated
     */
    public String getEqStatus() {
        return eqStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.eq_status
     *
     * @param eqStatus the value for csc_task_item.eq_status
     *
     * @mbggenerated
     */
    public void setEqStatus(String eqStatus) {
        this.eqStatus = eqStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.task_item_img
     *
     * @return the value of csc_task_item.task_item_img
     *
     * @mbggenerated
     */
    public String getTaskItemImg() {
        return taskItemImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.task_item_img
     *
     * @param taskItemImg the value for csc_task_item.task_item_img
     *
     * @mbggenerated
     */
    public void setTaskItemImg(String taskItemImg) {
        this.taskItemImg = taskItemImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.lj_remark
     *
     * @return the value of csc_task_item.lj_remark
     *
     * @mbggenerated
     */
    public String getLjRemark() {
        return ljRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.lj_remark
     *
     * @param ljRemark the value for csc_task_item.lj_remark
     *
     * @mbggenerated
     */
    public void setLjRemark(String ljRemark) {
        this.ljRemark = ljRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.remark_user
     *
     * @return the value of csc_task_item.remark_user
     *
     * @mbggenerated
     */
    public Long getRemarkUser() {
        return remarkUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.remark_user
     *
     * @param remarkUser the value for csc_task_item.remark_user
     *
     * @mbggenerated
     */
    public void setRemarkUser(Long remarkUser) {
        this.remarkUser = remarkUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.remark_time
     *
     * @return the value of csc_task_item.remark_time
     *
     * @mbggenerated
     */
    public Date getRemarkTime() {
        return remarkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.remark_time
     *
     * @param remarkTime the value for csc_task_item.remark_time
     *
     * @mbggenerated
     */
    public void setRemarkTime(Date remarkTime) {
        this.remarkTime = remarkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.remark_username
     *
     * @return the value of csc_task_item.remark_username
     *
     * @mbggenerated
     */
    public String getRemarkUsername() {
        return remarkUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.remark_username
     *
     * @param remarkUsername the value for csc_task_item.remark_username
     *
     * @mbggenerated
     */
    public void setRemarkUsername(String remarkUsername) {
        this.remarkUsername = remarkUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_item.df
     *
     * @return the value of csc_task_item.df
     *
     * @mbggenerated
     */
    public Boolean getDf() {
        return df;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_item.df
     *
     * @param df the value for csc_task_item.df
     *
     * @mbggenerated
     */
    public void setDf(Boolean df) {
        this.df = df;
    }
}