package com.hy.mybatis.entity;

import com.hy.mybatis.entity.base.BaseEntity;
import java.math.BigDecimal;
import java.util.Date;

public class CscTaskStation extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.task_station_id
     *
     * @mbggenerated
     */
    private Long taskStationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.task_id
     *
     * @mbggenerated
     */
    private Long taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.task_code
     *
     * @mbggenerated
     */
    private String taskCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.task_name
     *
     * @mbggenerated
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.line_id
     *
     * @mbggenerated
     */
    private Long lineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.line_name
     *
     * @mbggenerated
     */
    private String lineName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.station_id
     *
     * @mbggenerated
     */
    private Long stationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.station_name
     *
     * @mbggenerated
     */
    private String stationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.card_no
     *
     * @mbggenerated
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.check_item_count
     *
     * @mbggenerated
     */
    private Integer checkItemCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.checked_item_count
     *
     * @mbggenerated
     */
    private Integer checkedItemCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.fault_item_count
     *
     * @mbggenerated
     */
    private Integer faultItemCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.is_arrive
     *
     * @mbggenerated
     */
    private Boolean isArrive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.seq
     *
     * @mbggenerated
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.upload_per_id
     *
     * @mbggenerated
     */
    private Long uploadPerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.upload_per_name
     *
     * @mbggenerated
     */
    private String uploadPerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.upload_phone
     *
     * @mbggenerated
     */
    private String uploadPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.upload_time
     *
     * @mbggenerated
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.org_id
     *
     * @mbggenerated
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.org_name
     *
     * @mbggenerated
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.created_dt
     *
     * @mbggenerated
     */
    private Date createdDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.created_by
     *
     * @mbggenerated
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.updated_by
     *
     * @mbggenerated
     */
    private Long updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.updated_dt
     *
     * @mbggenerated
     */
    private Date updatedDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.created_by_name
     *
     * @mbggenerated
     */
    private String createdByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.updated_by_name
     *
     * @mbggenerated
     */
    private String updatedByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.tenantid
     *
     * @mbggenerated
     */
    private Long tenantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.ver
     *
     * @mbggenerated
     */
    private Integer ver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.blue_name
     *
     * @mbggenerated
     */
    private String blueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.blue_mac
     *
     * @mbggenerated
     */
    private String blueMac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.gps_x
     *
     * @mbggenerated
     */
    private BigDecimal gpsX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.gps_y
     *
     * @mbggenerated
     */
    private BigDecimal gpsY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.arrive_time
     *
     * @mbggenerated
     */
    private Date arriveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.stopcheck_state
     *
     * @mbggenerated
     */
    private String stopcheckState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.arrive_remark
     *
     * @mbggenerated
     */
    private String arriveRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.remark_user
     *
     * @mbggenerated
     */
    private Long remarkUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.remark_time
     *
     * @mbggenerated
     */
    private Date remarkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.remark_username
     *
     * @mbggenerated
     */
    private String remarkUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.remark_item_count
     *
     * @mbggenerated
     */
    private Integer remarkItemCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.station_start_time
     *
     * @mbggenerated
     */
    private Date stationStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.station_end_time
     *
     * @mbggenerated
     */
    private Date stationEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.station_set_time
     *
     * @mbggenerated
     */
    private Integer stationSetTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.station_real_time
     *
     * @mbggenerated
     */
    private Integer stationRealTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.sign_method_message
     *
     * @mbggenerated
     */
    private String signMethodMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.sign_method
     *
     * @mbggenerated
     */
    private String signMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.is_all_normal
     *
     * @mbggenerated
     */
    private Boolean isAllNormal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.df
     *
     * @mbggenerated
     */
    private Boolean df;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csc_task_station.on_check_item_count
     *
     * @mbggenerated
     */
    private Integer onCheckItemCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.task_station_id
     *
     * @return the value of csc_task_station.task_station_id
     *
     * @mbggenerated
     */
    public Long getTaskStationId() {
        return taskStationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.task_station_id
     *
     * @param taskStationId the value for csc_task_station.task_station_id
     *
     * @mbggenerated
     */
    public void setTaskStationId(Long taskStationId) {
        this.taskStationId = taskStationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.task_id
     *
     * @return the value of csc_task_station.task_id
     *
     * @mbggenerated
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.task_id
     *
     * @param taskId the value for csc_task_station.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.task_code
     *
     * @return the value of csc_task_station.task_code
     *
     * @mbggenerated
     */
    public String getTaskCode() {
        return taskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.task_code
     *
     * @param taskCode the value for csc_task_station.task_code
     *
     * @mbggenerated
     */
    public void setTaskCode(String taskCode) {
        this.taskCode = taskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.task_name
     *
     * @return the value of csc_task_station.task_name
     *
     * @mbggenerated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.task_name
     *
     * @param taskName the value for csc_task_station.task_name
     *
     * @mbggenerated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.line_id
     *
     * @return the value of csc_task_station.line_id
     *
     * @mbggenerated
     */
    public Long getLineId() {
        return lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.line_id
     *
     * @param lineId the value for csc_task_station.line_id
     *
     * @mbggenerated
     */
    public void setLineId(Long lineId) {
        this.lineId = lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.line_name
     *
     * @return the value of csc_task_station.line_name
     *
     * @mbggenerated
     */
    public String getLineName() {
        return lineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.line_name
     *
     * @param lineName the value for csc_task_station.line_name
     *
     * @mbggenerated
     */
    public void setLineName(String lineName) {
        this.lineName = lineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.station_id
     *
     * @return the value of csc_task_station.station_id
     *
     * @mbggenerated
     */
    public Long getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.station_id
     *
     * @param stationId the value for csc_task_station.station_id
     *
     * @mbggenerated
     */
    public void setStationId(Long stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.station_name
     *
     * @return the value of csc_task_station.station_name
     *
     * @mbggenerated
     */
    public String getStationName() {
        return stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.station_name
     *
     * @param stationName the value for csc_task_station.station_name
     *
     * @mbggenerated
     */
    public void setStationName(String stationName) {
        this.stationName = stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.card_no
     *
     * @return the value of csc_task_station.card_no
     *
     * @mbggenerated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.card_no
     *
     * @param cardNo the value for csc_task_station.card_no
     *
     * @mbggenerated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.check_item_count
     *
     * @return the value of csc_task_station.check_item_count
     *
     * @mbggenerated
     */
    public Integer getCheckItemCount() {
        return checkItemCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.check_item_count
     *
     * @param checkItemCount the value for csc_task_station.check_item_count
     *
     * @mbggenerated
     */
    public void setCheckItemCount(Integer checkItemCount) {
        this.checkItemCount = checkItemCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.checked_item_count
     *
     * @return the value of csc_task_station.checked_item_count
     *
     * @mbggenerated
     */
    public Integer getCheckedItemCount() {
        return checkedItemCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.checked_item_count
     *
     * @param checkedItemCount the value for csc_task_station.checked_item_count
     *
     * @mbggenerated
     */
    public void setCheckedItemCount(Integer checkedItemCount) {
        this.checkedItemCount = checkedItemCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.fault_item_count
     *
     * @return the value of csc_task_station.fault_item_count
     *
     * @mbggenerated
     */
    public Integer getFaultItemCount() {
        return faultItemCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.fault_item_count
     *
     * @param faultItemCount the value for csc_task_station.fault_item_count
     *
     * @mbggenerated
     */
    public void setFaultItemCount(Integer faultItemCount) {
        this.faultItemCount = faultItemCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.is_arrive
     *
     * @return the value of csc_task_station.is_arrive
     *
     * @mbggenerated
     */
    public Boolean getIsArrive() {
        return isArrive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.is_arrive
     *
     * @param isArrive the value for csc_task_station.is_arrive
     *
     * @mbggenerated
     */
    public void setIsArrive(Boolean isArrive) {
        this.isArrive = isArrive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.seq
     *
     * @return the value of csc_task_station.seq
     *
     * @mbggenerated
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.seq
     *
     * @param seq the value for csc_task_station.seq
     *
     * @mbggenerated
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.upload_per_id
     *
     * @return the value of csc_task_station.upload_per_id
     *
     * @mbggenerated
     */
    public Long getUploadPerId() {
        return uploadPerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.upload_per_id
     *
     * @param uploadPerId the value for csc_task_station.upload_per_id
     *
     * @mbggenerated
     */
    public void setUploadPerId(Long uploadPerId) {
        this.uploadPerId = uploadPerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.upload_per_name
     *
     * @return the value of csc_task_station.upload_per_name
     *
     * @mbggenerated
     */
    public String getUploadPerName() {
        return uploadPerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.upload_per_name
     *
     * @param uploadPerName the value for csc_task_station.upload_per_name
     *
     * @mbggenerated
     */
    public void setUploadPerName(String uploadPerName) {
        this.uploadPerName = uploadPerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.upload_phone
     *
     * @return the value of csc_task_station.upload_phone
     *
     * @mbggenerated
     */
    public String getUploadPhone() {
        return uploadPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.upload_phone
     *
     * @param uploadPhone the value for csc_task_station.upload_phone
     *
     * @mbggenerated
     */
    public void setUploadPhone(String uploadPhone) {
        this.uploadPhone = uploadPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.upload_time
     *
     * @return the value of csc_task_station.upload_time
     *
     * @mbggenerated
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.upload_time
     *
     * @param uploadTime the value for csc_task_station.upload_time
     *
     * @mbggenerated
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.org_id
     *
     * @return the value of csc_task_station.org_id
     *
     * @mbggenerated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.org_id
     *
     * @param orgId the value for csc_task_station.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.org_name
     *
     * @return the value of csc_task_station.org_name
     *
     * @mbggenerated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.org_name
     *
     * @param orgName the value for csc_task_station.org_name
     *
     * @mbggenerated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.created_dt
     *
     * @return the value of csc_task_station.created_dt
     *
     * @mbggenerated
     */
    public Date getCreatedDt() {
        return createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.created_dt
     *
     * @param createdDt the value for csc_task_station.created_dt
     *
     * @mbggenerated
     */
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.created_by
     *
     * @return the value of csc_task_station.created_by
     *
     * @mbggenerated
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.created_by
     *
     * @param createdBy the value for csc_task_station.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.updated_by
     *
     * @return the value of csc_task_station.updated_by
     *
     * @mbggenerated
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.updated_by
     *
     * @param updatedBy the value for csc_task_station.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.updated_dt
     *
     * @return the value of csc_task_station.updated_dt
     *
     * @mbggenerated
     */
    public Date getUpdatedDt() {
        return updatedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.updated_dt
     *
     * @param updatedDt the value for csc_task_station.updated_dt
     *
     * @mbggenerated
     */
    public void setUpdatedDt(Date updatedDt) {
        this.updatedDt = updatedDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.created_by_name
     *
     * @return the value of csc_task_station.created_by_name
     *
     * @mbggenerated
     */
    public String getCreatedByName() {
        return createdByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.created_by_name
     *
     * @param createdByName the value for csc_task_station.created_by_name
     *
     * @mbggenerated
     */
    public void setCreatedByName(String createdByName) {
        this.createdByName = createdByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.updated_by_name
     *
     * @return the value of csc_task_station.updated_by_name
     *
     * @mbggenerated
     */
    public String getUpdatedByName() {
        return updatedByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.updated_by_name
     *
     * @param updatedByName the value for csc_task_station.updated_by_name
     *
     * @mbggenerated
     */
    public void setUpdatedByName(String updatedByName) {
        this.updatedByName = updatedByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.tenantid
     *
     * @return the value of csc_task_station.tenantid
     *
     * @mbggenerated
     */
    public Long getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.tenantid
     *
     * @param tenantid the value for csc_task_station.tenantid
     *
     * @mbggenerated
     */
    public void setTenantid(Long tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.ver
     *
     * @return the value of csc_task_station.ver
     *
     * @mbggenerated
     */
    public Integer getVer() {
        return ver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.ver
     *
     * @param ver the value for csc_task_station.ver
     *
     * @mbggenerated
     */
    public void setVer(Integer ver) {
        this.ver = ver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.blue_name
     *
     * @return the value of csc_task_station.blue_name
     *
     * @mbggenerated
     */
    public String getBlueName() {
        return blueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.blue_name
     *
     * @param blueName the value for csc_task_station.blue_name
     *
     * @mbggenerated
     */
    public void setBlueName(String blueName) {
        this.blueName = blueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.blue_mac
     *
     * @return the value of csc_task_station.blue_mac
     *
     * @mbggenerated
     */
    public String getBlueMac() {
        return blueMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.blue_mac
     *
     * @param blueMac the value for csc_task_station.blue_mac
     *
     * @mbggenerated
     */
    public void setBlueMac(String blueMac) {
        this.blueMac = blueMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.gps_x
     *
     * @return the value of csc_task_station.gps_x
     *
     * @mbggenerated
     */
    public BigDecimal getGpsX() {
        return gpsX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.gps_x
     *
     * @param gpsX the value for csc_task_station.gps_x
     *
     * @mbggenerated
     */
    public void setGpsX(BigDecimal gpsX) {
        this.gpsX = gpsX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.gps_y
     *
     * @return the value of csc_task_station.gps_y
     *
     * @mbggenerated
     */
    public BigDecimal getGpsY() {
        return gpsY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.gps_y
     *
     * @param gpsY the value for csc_task_station.gps_y
     *
     * @mbggenerated
     */
    public void setGpsY(BigDecimal gpsY) {
        this.gpsY = gpsY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.arrive_time
     *
     * @return the value of csc_task_station.arrive_time
     *
     * @mbggenerated
     */
    public Date getArriveTime() {
        return arriveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.arrive_time
     *
     * @param arriveTime the value for csc_task_station.arrive_time
     *
     * @mbggenerated
     */
    public void setArriveTime(Date arriveTime) {
        this.arriveTime = arriveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.stopcheck_state
     *
     * @return the value of csc_task_station.stopcheck_state
     *
     * @mbggenerated
     */
    public String getStopcheckState() {
        return stopcheckState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.stopcheck_state
     *
     * @param stopcheckState the value for csc_task_station.stopcheck_state
     *
     * @mbggenerated
     */
    public void setStopcheckState(String stopcheckState) {
        this.stopcheckState = stopcheckState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.arrive_remark
     *
     * @return the value of csc_task_station.arrive_remark
     *
     * @mbggenerated
     */
    public String getArriveRemark() {
        return arriveRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.arrive_remark
     *
     * @param arriveRemark the value for csc_task_station.arrive_remark
     *
     * @mbggenerated
     */
    public void setArriveRemark(String arriveRemark) {
        this.arriveRemark = arriveRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.remark_user
     *
     * @return the value of csc_task_station.remark_user
     *
     * @mbggenerated
     */
    public Long getRemarkUser() {
        return remarkUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.remark_user
     *
     * @param remarkUser the value for csc_task_station.remark_user
     *
     * @mbggenerated
     */
    public void setRemarkUser(Long remarkUser) {
        this.remarkUser = remarkUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.remark_time
     *
     * @return the value of csc_task_station.remark_time
     *
     * @mbggenerated
     */
    public Date getRemarkTime() {
        return remarkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.remark_time
     *
     * @param remarkTime the value for csc_task_station.remark_time
     *
     * @mbggenerated
     */
    public void setRemarkTime(Date remarkTime) {
        this.remarkTime = remarkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.remark_username
     *
     * @return the value of csc_task_station.remark_username
     *
     * @mbggenerated
     */
    public String getRemarkUsername() {
        return remarkUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.remark_username
     *
     * @param remarkUsername the value for csc_task_station.remark_username
     *
     * @mbggenerated
     */
    public void setRemarkUsername(String remarkUsername) {
        this.remarkUsername = remarkUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.remark_item_count
     *
     * @return the value of csc_task_station.remark_item_count
     *
     * @mbggenerated
     */
    public Integer getRemarkItemCount() {
        return remarkItemCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.remark_item_count
     *
     * @param remarkItemCount the value for csc_task_station.remark_item_count
     *
     * @mbggenerated
     */
    public void setRemarkItemCount(Integer remarkItemCount) {
        this.remarkItemCount = remarkItemCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.station_start_time
     *
     * @return the value of csc_task_station.station_start_time
     *
     * @mbggenerated
     */
    public Date getStationStartTime() {
        return stationStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.station_start_time
     *
     * @param stationStartTime the value for csc_task_station.station_start_time
     *
     * @mbggenerated
     */
    public void setStationStartTime(Date stationStartTime) {
        this.stationStartTime = stationStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.station_end_time
     *
     * @return the value of csc_task_station.station_end_time
     *
     * @mbggenerated
     */
    public Date getStationEndTime() {
        return stationEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.station_end_time
     *
     * @param stationEndTime the value for csc_task_station.station_end_time
     *
     * @mbggenerated
     */
    public void setStationEndTime(Date stationEndTime) {
        this.stationEndTime = stationEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.station_set_time
     *
     * @return the value of csc_task_station.station_set_time
     *
     * @mbggenerated
     */
    public Integer getStationSetTime() {
        return stationSetTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.station_set_time
     *
     * @param stationSetTime the value for csc_task_station.station_set_time
     *
     * @mbggenerated
     */
    public void setStationSetTime(Integer stationSetTime) {
        this.stationSetTime = stationSetTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.station_real_time
     *
     * @return the value of csc_task_station.station_real_time
     *
     * @mbggenerated
     */
    public Integer getStationRealTime() {
        return stationRealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.station_real_time
     *
     * @param stationRealTime the value for csc_task_station.station_real_time
     *
     * @mbggenerated
     */
    public void setStationRealTime(Integer stationRealTime) {
        this.stationRealTime = stationRealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.sign_method_message
     *
     * @return the value of csc_task_station.sign_method_message
     *
     * @mbggenerated
     */
    public String getSignMethodMessage() {
        return signMethodMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.sign_method_message
     *
     * @param signMethodMessage the value for csc_task_station.sign_method_message
     *
     * @mbggenerated
     */
    public void setSignMethodMessage(String signMethodMessage) {
        this.signMethodMessage = signMethodMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.sign_method
     *
     * @return the value of csc_task_station.sign_method
     *
     * @mbggenerated
     */
    public String getSignMethod() {
        return signMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.sign_method
     *
     * @param signMethod the value for csc_task_station.sign_method
     *
     * @mbggenerated
     */
    public void setSignMethod(String signMethod) {
        this.signMethod = signMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.is_all_normal
     *
     * @return the value of csc_task_station.is_all_normal
     *
     * @mbggenerated
     */
    public Boolean getIsAllNormal() {
        return isAllNormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.is_all_normal
     *
     * @param isAllNormal the value for csc_task_station.is_all_normal
     *
     * @mbggenerated
     */
    public void setIsAllNormal(Boolean isAllNormal) {
        this.isAllNormal = isAllNormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.df
     *
     * @return the value of csc_task_station.df
     *
     * @mbggenerated
     */
    public Boolean getDf() {
        return df;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.df
     *
     * @param df the value for csc_task_station.df
     *
     * @mbggenerated
     */
    public void setDf(Boolean df) {
        this.df = df;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csc_task_station.on_check_item_count
     *
     * @return the value of csc_task_station.on_check_item_count
     *
     * @mbggenerated
     */
    public Integer getOnCheckItemCount() {
        return onCheckItemCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csc_task_station.on_check_item_count
     *
     * @param onCheckItemCount the value for csc_task_station.on_check_item_count
     *
     * @mbggenerated
     */
    public void setOnCheckItemCount(Integer onCheckItemCount) {
        this.onCheckItemCount = onCheckItemCount;
    }
}