package com.hy.demo.mybatis.mapper;

import com.hy.demo.mybatis.entity.CscLine;

import java.util.List;

public interface CscLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csc_line
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long lineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csc_line
     *
     * @mbggenerated
     */
    int insert(CscLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csc_line
     *
     * @mbggenerated
     */
    int insertSelective(CscLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csc_line
     *
     * @mbggenerated
     */
    CscLine selectByPrimaryKey(Long lineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csc_line
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CscLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csc_line
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CscLine record);

    List<CscLine> list();
}